import type { RAM } from "@/lib/types/components";

export const ramBatch3: RAM[] = [
  {
    id: "ram-ddr4-16gb-3600-crucial",
    name: "16GB DDR4-3600 (2x8GB)",
    brand: "Crucial",
    model: "Ballistix 16GB DDR4-3600",
    category: "ram",
    performanceTier: "mid",
    pricing: { usedMin: 28, usedMax: 42, newMin: 50, newMax: 65 },
    type: "DDR4",
    capacityGb: 16,
    speedMhz: 3600,
    modules: 2,
    rgb: false,
    specsSummary: "Common gaming kit. Micron dies — reliable flip RAM.",
    tags: ["gaming", "popular"],
  },
  {
    id: "ram-ddr4-32gb-3200-team",
    name: "32GB DDR4-3200 (2x16GB)",
    brand: "TeamGroup",
    model: "T-Force Vulcan 32GB DDR4-3200",
    category: "ram",
    performanceTier: "mid",
    pricing: { usedMin: 40, usedMax: 58, newMin: 65, newMax: 80 },
    type: "DDR4",
    capacityGb: 32,
    speedMhz: 3200,
    modules: 2,
    rgb: false,
    specsSummary: "Budget 32GB kit. Good value for productivity flips.",
    tags: ["32gb", "value"],
  },
  {
    id: "ram-ddr5-32gb-5200",
    name: "32GB DDR5-5200 (2x16GB)",
    brand: "Kingston",
    model: "Fury Beast 32GB DDR5-5200",
    category: "ram",
    performanceTier: "mid",
    pricing: { usedMin: 70, usedMax: 95, newMin: 100, newMax: 125 },
    type: "DDR5",
    capacityGb: 32,
    speedMhz: 5200,
    modules: 2,
    rgb: false,
    specsSummary: "Entry DDR5 32GB. Common on budget AM5 builds.",
    tags: ["ddr5", "32gb"],
  },
  {
    id: "ram-ddr5-32gb-6400",
    name: "32GB DDR5-6400 (2x16GB)",
    brand: "G.Skill",
    model: "Trident Z5 32GB DDR5-6400",
    category: "ram",
    performanceTier: "high",
    pricing: { usedMin: 100, usedMax: 135, newMin: 140, newMax: 170 },
    type: "DDR5",
    capacityGb: 32,
    speedMhz: 6400,
    modules: 2,
    rgb: true,
    specsSummary: "Fast DDR5 for Ryzen 7000/9000. Sweet spot speed.",
    tags: ["ddr5", "high-speed"],
  },
  {
    id: "ram-ddr4-16gb-2400-oem",
    name: "16GB DDR4-2400 (2x8GB)",
    brand: "Samsung",
    model: "OEM DDR4-2400 16GB",
    category: "ram",
    performanceTier: "entry",
    pricing: { usedMin: 12, usedMax: 22, newMin: 0, newMax: 0 },
    type: "DDR4",
    capacityGb: 16,
    speedMhz: 2400,
    modules: 2,
    rgb: false,
    specsSummary: "Slow OEM sticks from Dell/HP. Flag as upgrade needed.",
    tags: ["oem", "slow", "upgrade-candidate"],
  },
  {
    id: "ram-ddr5-48gb-6000",
    name: "48GB DDR5-6000 (2x24GB)",
    brand: "Corsair",
    model: "Vengeance 48GB DDR5-6000",
    category: "ram",
    performanceTier: "high",
    pricing: { usedMin: 120, usedMax: 160, newMin: 0, newMax: 0 },
    type: "DDR5",
    capacityGb: 48,
    speedMhz: 6000,
    modules: 2,
    rgb: false,
    specsSummary: "Non-standard 24GB modules. Verify motherboard QVL.",
    tags: ["ddr5", "unusual"],
  },
];
