import type { RAM } from "@/lib/types/components";

export const ramExtended: RAM[] = [
  {
    id: "ram-ddr4-32gb-3200",
    name: "32GB DDR4-3200 (2x16GB)",
    brand: "Corsair",
    model: "Vengeance LPX 32GB DDR4-3200",
    category: "ram",
    performanceTier: "mid",
    pricing: { usedMin: 45, usedMax: 65, newMin: 70, newMax: 90 },
    type: "DDR4",
    capacityGb: 32,
    speedMhz: 3200,
    modules: 2,
    rgb: false,
    specsSummary: "Sweet spot for productivity and gaming flips.",
    tags: ["32gb", "productivity"],
  },
  {
    id: "ram-ddr4-64gb-3600",
    name: "64GB DDR4-3600 (2x32GB)",
    brand: "G.Skill",
    model: "Ripjaws V 64GB DDR4-3600",
    category: "ram",
    performanceTier: "high",
    pricing: { usedMin: 100, usedMax: 140, newMin: 0, newMax: 0 },
    type: "DDR4",
    capacityGb: 64,
    speedMhz: 3600,
    modules: 2,
    rgb: false,
    specsSummary: "Workstation-tier DDR4. Adds resale appeal for creators.",
    tags: ["workstation", "64gb"],
  },
  {
    id: "ram-ddr5-16gb-6000",
    name: "16GB DDR5-6000 (2x8GB)",
    brand: "Corsair",
    model: "Dominator DDR5-6000 16GB",
    category: "ram",
    performanceTier: "mid",
    pricing: { usedMin: 50, usedMax: 70, newMin: 80, newMax: 100 },
    type: "DDR5",
    capacityGb: 16,
    speedMhz: 6000,
    modules: 2,
    rgb: true,
    specsSummary: "Entry AM5 DDR5 kit. Minimum for modern builds.",
    tags: ["ddr5", "am5"],
  },
  {
    id: "ram-ddr5-64gb-6000",
    name: "64GB DDR5-6000 (2x32GB)",
    brand: "G.Skill",
    model: "Trident Z5 64GB DDR5-6000",
    category: "ram",
    performanceTier: "enthusiast",
    pricing: { usedMin: 180, usedMax: 240, newMin: 0, newMax: 0 },
    type: "DDR5",
    capacityGb: 64,
    speedMhz: 6000,
    modules: 2,
    rgb: true,
    specsSummary: "High-end DDR5. Premium workstation flip component.",
    tags: ["ddr5", "workstation"],
  },
  {
    id: "ram-ddr4-16gb-2666",
    name: "16GB DDR4-2666 (2x8GB)",
    brand: "Generic",
    model: "DDR4-2666 16GB",
    category: "ram",
    performanceTier: "entry",
    pricing: { usedMin: 15, usedMax: 25, newMin: 0, newMax: 0 },
    type: "DDR4",
    capacityGb: 16,
    speedMhz: 2666,
    modules: 2,
    rgb: false,
    specsSummary: "Slow OEM RAM from prebuilts. Upgrade candidate.",
    tags: ["oem", "slow", "upgrade-candidate"],
  },
];
