import type { PSU } from "@/lib/types/components";

export const psuBatch3: PSU[] = [
  {
    id: "psu-750w-gold-corsair",
    name: "750W 80+ Gold",
    brand: "Corsair",
    model: "RM750x",
    category: "psu",
    performanceTier: "high",
    pricing: { usedMin: 70, usedMax: 100, newMin: 110, newMax: 140 },
    wattage: 750,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin"],
    sataConnectors: 10,
    epsConnectors: 1,
    specsSummary: "Standard for RTX 3070/4070 class builds.",
    tags: ["750w", "popular"],
  },
  {
    id: "psu-1000w-gold",
    name: "1000W 80+ Gold",
    brand: "Corsair",
    model: "HX1000i",
    category: "psu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 130, usedMax: 180, newMin: 0, newMax: 0 },
    wattage: 1000,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin", "6+2-pin", "6+2-pin"],
    sataConnectors: 12,
    epsConnectors: 1,
    specsSummary: "High-wattage for RTX 4080/4090 flips.",
    tags: ["1000w", "high-end"],
  },
  {
    id: "psu-550w-white-evga",
    name: "550W 80+ White",
    brand: "EVGA",
    model: "500/600 W1",
    category: "psu",
    performanceTier: "entry",
    pricing: { usedMin: 15, usedMax: 30, newMin: 0, newMax: 0 },
    wattage: 550,
    efficiency: "White",
    modular: "non-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin"],
    sataConnectors: 4,
    epsConnectors: 1,
    specsSummary: "Low-tier PSU from prebuilts. Replace before premium flip.",
    tags: ["weak", "prebuilt"],
  },
  {
    id: "psu-650w-bronze",
    name: "650W 80+ Bronze",
    brand: "Thermaltake",
    model: "Smart BM2 650W",
    category: "psu",
    performanceTier: "budget",
    pricing: { usedMin: 35, usedMax: 55, newMin: 60, newMax: 75 },
    wattage: 650,
    efficiency: "Bronze",
    modular: "semi-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin"],
    sataConnectors: 6,
    epsConnectors: 1,
    specsSummary: "Common budget PSU. OK for mid-tier GPU builds.",
    tags: ["budget", "650w"],
  },
];
