import type { PSU } from "@/lib/types/components";

export const psuExtended: PSU[] = [
  {
    id: "psu-500w-bronze",
    name: "500W 80+ Bronze",
    brand: "EVGA",
    model: "500 BR",
    category: "psu",
    performanceTier: "budget",
    pricing: { usedMin: 25, usedMax: 40, newMin: 45, newMax: 60 },
    wattage: 500,
    efficiency: "Bronze",
    modular: "non-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin"],
    sataConnectors: 6,
    epsConnectors: 1,
    specsSummary: "Minimum for budget GPUs. Replace in premium flips.",
    tags: ["budget", "weak"],
  },
  {
    id: "psu-600w-gold",
    name: "600W 80+ Gold",
    brand: "Corsair",
    model: "RM600x",
    category: "psu",
    performanceTier: "mid",
    pricing: { usedMin: 55, usedMax: 80, newMin: 90, newMax: 110 },
    wattage: 600,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin"],
    sataConnectors: 8,
    epsConnectors: 1,
    specsSummary: "Reliable mid-tier PSU for RTX 3060/4060 class builds.",
    tags: ["reliable", "gaming"],
  },
  {
    id: "psu-850w-platinum",
    name: "850W 80+ Platinum",
    brand: "Seasonic",
    model: "PRIME TX-850",
    category: "psu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 120, usedMax: 170, newMin: 0, newMax: 0 },
    wattage: 850,
    efficiency: "Platinum",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin", "6+2-pin", "6+2-pin"],
    sataConnectors: 12,
    epsConnectors: 1,
    specsSummary: "Top-tier PSU. Adds credibility to high-end flips.",
    tags: ["premium", "high-wattage"],
  },
  {
    id: "psu-sfx-650w",
    name: "650W SFX 80+ Gold",
    brand: "Corsair",
    model: "SF650",
    category: "psu",
    performanceTier: "high",
    pricing: { usedMin: 80, usedMax: 110, newMin: 130, newMax: 150 },
    wattage: 650,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "SFX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin"],
    sataConnectors: 4,
    epsConnectors: 1,
    specsSummary: "SFF PSU for ITX builds. Niche but valuable.",
    tags: ["sfx", "itx"],
  },
];
