import type { PSU } from "@/lib/types/components";

export const psus: PSU[] = [
  {
    id: "psu-450w-bronze",
    name: "450W 80+ Bronze",
    brand: "EVGA",
    model: "450 BR 450W",
    category: "psu",
    performanceTier: "budget",
    pricing: { usedMin: 20, usedMax: 35, newMin: 40, newMax: 55 },
    wattage: 450,
    efficiency: "Bronze",
    modular: "non-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin"],
    sataConnectors: 4,
    epsConnectors: 1,
    tags: ["budget", "weak"],
  },
  {
    id: "psu-550w-gold",
    name: "550W 80+ Gold",
    brand: "Corsair",
    model: "RM550x",
    category: "psu",
    performanceTier: "mid",
    pricing: { usedMin: 40, usedMax: 60, newMin: 70, newMax: 90 },
    wattage: 550,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin"],
    sataConnectors: 8,
    epsConnectors: 1,
    tags: ["reliable"],
  },
  {
    id: "psu-650w-gold",
    name: "650W 80+ Gold",
    brand: "Corsair",
    model: "RM650x",
    category: "psu",
    performanceTier: "mid",
    pricing: { usedMin: 50, usedMax: 75, newMin: 85, newMax: 110 },
    wattage: 650,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin"],
    sataConnectors: 8,
    epsConnectors: 1,
    tags: ["popular", "gaming"],
  },
  {
    id: "psu-750w-gold",
    name: "750W 80+ Gold",
    brand: "Seasonic",
    model: "FOCUS GX-750",
    category: "psu",
    performanceTier: "high",
    pricing: { usedMin: 65, usedMax: 95, newMin: 100, newMax: 130 },
    wattage: 750,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin", "6+2-pin"],
    sataConnectors: 10,
    epsConnectors: 1,
    tags: ["high-end"],
  },
  {
    id: "psu-850w-gold",
    name: "850W 80+ Gold",
    brand: "EVGA",
    model: "SuperNOVA 850 G6",
    category: "psu",
    performanceTier: "high",
    pricing: { usedMin: 80, usedMax: 110, newMin: 120, newMax: 150 },
    wattage: 850,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin", "6+2-pin", "6+2-pin"],
    sataConnectors: 12,
    epsConnectors: 1,
    tags: ["enthusiast"],
  },
];
