import type { Storage } from "@/lib/types/components";

export const storageBatch3: Storage[] = [
  {
    id: "ssd-nvme-500gb-crucial",
    name: "500GB NVMe SSD",
    brand: "Crucial",
    model: "P3 500GB",
    category: "storage",
    performanceTier: "budget",
    pricing: { usedMin: 25, usedMax: 38, newMin: 40, newMax: 55 },
    type: "NVMe",
    capacityGb: 500,
    interface: "NVMe PCIe 3.0",
    formFactor: "M.2",
    readSpeedMbps: 3500,
    writeSpeedMbps: 1900,
    specsSummary: "Budget boot drive. Minimum acceptable for gaming flips.",
    tags: ["budget", "boot"],
  },
  {
    id: "ssd-nvme-1tb-wd-blue",
    name: "1TB NVMe SSD",
    brand: "WD",
    model: "Blue SN580 1TB",
    category: "storage",
    performanceTier: "mid",
    pricing: { usedMin: 45, usedMax: 65, newMin: 70, newMax: 90 },
    type: "NVMe",
    capacityGb: 1000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 4150,
    writeSpeedMbps: 3900,
    specsSummary: "Solid mid-tier 1TB NVMe. Common upgrade from HDD.",
    tags: ["1tb", "popular"],
  },
  {
    id: "ssd-nvme-2tb-samsung-980",
    name: "2TB NVMe SSD",
    brand: "Samsung",
    model: "980 PRO 2TB",
    category: "storage",
    performanceTier: "high",
    pricing: { usedMin: 110, usedMax: 150, newMin: 160, newMax: 190 },
    type: "NVMe",
    capacityGb: 2000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 7000,
    writeSpeedMbps: 5100,
    specsSummary: "Samsung 980 PRO — buyers recognize and trust this drive.",
    tags: ["premium", "2tb"],
  },
  {
    id: "ssd-nvme-1tb-kingston",
    name: "1TB NVMe SSD",
    brand: "Kingston",
    model: "NV2 1TB",
    category: "storage",
    performanceTier: "budget",
    pricing: { usedMin: 35, usedMax: 50, newMin: 55, newMax: 70 },
    type: "NVMe",
    capacityGb: 1000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 3500,
    writeSpeedMbps: 2100,
    specsSummary: "Cheap 1TB NVMe. Fine for budget flips.",
    tags: ["budget", "1tb"],
  },
  {
    id: "hdd-2tb-7200",
    name: "2TB HDD 7200RPM",
    brand: "WD",
    model: "Black 2TB 7200RPM",
    category: "storage",
    performanceTier: "budget",
    pricing: { usedMin: 30, usedMax: 45, newMin: 55, newMax: 70 },
    type: "HDD",
    capacityGb: 2000,
    interface: "SATA III",
    formFactor: "3.5\"",
    readSpeedMbps: 200,
    writeSpeedMbps: 200,
    specsSummary: "Game/storage drive. Replace with SSD for better flip value.",
    tags: ["hdd", "upgrade-candidate"],
  },
  {
    id: "ssd-sata-500gb",
    name: "500GB SATA SSD",
    brand: "Crucial",
    model: "MX500 500GB",
    category: "storage",
    performanceTier: "budget",
    pricing: { usedMin: 25, usedMax: 38, newMin: 40, newMax: 55 },
    type: "SATA SSD",
    capacityGb: 500,
    interface: "SATA III",
    formFactor: "2.5\"",
    readSpeedMbps: 560,
    writeSpeedMbps: 510,
    specsSummary: "Legacy SATA SSD. Common in older prebuilts.",
    tags: ["sata", "legacy"],
  },
];
