import type { Storage } from "@/lib/types/components";

export const storageExtended: Storage[] = [
  {
    id: "ssd-nvme-256gb",
    name: "256GB NVMe SSD",
    brand: "WD",
    model: "SN570 256GB",
    category: "storage",
    performanceTier: "budget",
    pricing: { usedMin: 18, usedMax: 28, newMin: 30, newMax: 40 },
    type: "NVMe",
    capacityGb: 256,
    interface: "NVMe PCIe 3.0",
    formFactor: "M.2",
    readSpeedMbps: 3300,
    writeSpeedMbps: 1200,
    specsSummary: "Bare minimum boot drive. Upgrade for better resale.",
    tags: ["weak", "upgrade-candidate"],
  },
  {
    id: "ssd-nvme-2tb-samsung",
    name: "2TB NVMe SSD",
    brand: "Samsung",
    model: "990 PRO 2TB",
    category: "storage",
    performanceTier: "high",
    pricing: { usedMin: 120, usedMax: 160, newMin: 170, newMax: 200 },
    type: "NVMe",
    capacityGb: 2000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 7450,
    writeSpeedMbps: 6900,
    specsSummary: "Premium Gen4 drive. Buyers love 2TB Samsung.",
    tags: ["high-capacity", "premium"],
  },
  {
    id: "ssd-sata-1tb",
    name: "1TB SATA SSD",
    brand: "Samsung",
    model: "870 EVO 1TB",
    category: "storage",
    performanceTier: "mid",
    pricing: { usedMin: 45, usedMax: 65, newMin: 70, newMax: 90 },
    type: "SATA SSD",
    capacityGb: 1000,
    interface: "SATA III",
    formFactor: "2.5\"",
    readSpeedMbps: 560,
    writeSpeedMbps: 530,
    specsSummary: "Reliable secondary/game drive. Common upgrade from HDD.",
    tags: ["sata", "upgrade"],
  },
  {
    id: "ssd-nvme-4tb",
    name: "4TB NVMe SSD",
    brand: "Crucial",
    model: "P3 Plus 4TB",
    category: "storage",
    performanceTier: "high",
    pricing: { usedMin: 200, usedMax: 280, newMin: 0, newMax: 0 },
    type: "NVMe",
    capacityGb: 4000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 4800,
    writeSpeedMbps: 4200,
    specsSummary: "Mass storage NVMe. Appeals to creators and gamers.",
    tags: ["high-capacity"],
  },
  {
    id: "hdd-4tb",
    name: "4TB HDD 5400RPM",
    brand: "Seagate",
    model: "Barracuda 4TB",
    category: "storage",
    performanceTier: "entry",
    pricing: { usedMin: 40, usedMax: 60, newMin: 70, newMax: 90 },
    type: "HDD",
    capacityGb: 4000,
    interface: "SATA III",
    formFactor: "3.5\"",
    readSpeedMbps: 180,
    writeSpeedMbps: 180,
    specsSummary: "Bulk storage only. Pair with NVMe boot drive.",
    tags: ["storage", "slow"],
  },
];
