import type { Storage } from "@/lib/types/components";

export const nvmeSSDs: Storage[] = [
  {
    id: "ssd-nvme-250gb",
    name: "250GB NVMe SSD",
    brand: "Generic",
    model: "250GB NVMe PCIe 3.0",
    category: "storage",
    performanceTier: "budget",
    pricing: { usedMin: 15, usedMax: 25, newMin: 25, newMax: 35 },
    type: "NVMe",
    capacityGb: 250,
    interface: "NVMe PCIe 3.0",
    formFactor: "M.2",
    readSpeedMbps: 2000,
    writeSpeedMbps: 1500,
    tags: ["weak", "upgrade-candidate"],
  },
  {
    id: "ssd-nvme-500gb",
    name: "500GB NVMe SSD",
    brand: "Samsung",
    model: "970 EVO Plus 500GB",
    category: "storage",
    performanceTier: "mid",
    pricing: { usedMin: 30, usedMax: 45, newMin: 50, newMax: 65 },
    type: "NVMe",
    capacityGb: 500,
    interface: "NVMe PCIe 3.0",
    formFactor: "M.2",
    readSpeedMbps: 3500,
    writeSpeedMbps: 3200,
    tags: ["common"],
  },
  {
    id: "ssd-nvme-1tb",
    name: "1TB NVMe SSD",
    brand: "Samsung",
    model: "980 PRO 1TB",
    category: "storage",
    performanceTier: "mid",
    pricing: { usedMin: 55, usedMax: 75, newMin: 80, newMax: 100 },
    type: "NVMe",
    capacityGb: 1000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 7000,
    writeSpeedMbps: 5000,
    tags: ["recommended-upgrade"],
  },
  {
    id: "ssd-nvme-2tb",
    name: "2TB NVMe SSD",
    brand: "WD",
    model: "SN850X 2TB",
    category: "storage",
    performanceTier: "high",
    pricing: { usedMin: 100, usedMax: 140, newMin: 150, newMax: 180 },
    type: "NVMe",
    capacityGb: 2000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 7300,
    writeSpeedMbps: 6600,
    tags: ["high-capacity"],
  },
];

export const sataSSDs: Storage[] = [
  {
    id: "ssd-sata-500gb",
    name: "500GB SATA SSD",
    brand: "Crucial",
    model: "MX500 500GB",
    category: "storage",
    performanceTier: "budget",
    pricing: { usedMin: 25, usedMax: 40, newMin: 45, newMax: 55 },
    type: "SATA SSD",
    capacityGb: 500,
    interface: "SATA III",
    formFactor: "2.5\"",
    readSpeedMbps: 560,
    writeSpeedMbps: 510,
    tags: ["legacy"],
  },
];

export const hdds: Storage[] = [
  {
    id: "hdd-1tb",
    name: "1TB HDD 7200RPM",
    brand: "Seagate",
    model: "Barracuda 1TB",
    category: "storage",
    performanceTier: "entry",
    pricing: { usedMin: 15, usedMax: 25, newMin: 35, newMax: 45 },
    type: "HDD",
    capacityGb: 1000,
    interface: "SATA III",
    formFactor: "3.5\"",
    readSpeedMbps: 180,
    writeSpeedMbps: 180,
    tags: ["slow", "upgrade-candidate"],
  },
  {
    id: "hdd-2tb",
    name: "2TB HDD 7200RPM",
    brand: "WD",
    model: "Blue 2TB",
    category: "storage",
    performanceTier: "entry",
    pricing: { usedMin: 25, usedMax: 40, newMin: 50, newMax: 60 },
    type: "HDD",
    capacityGb: 2000,
    interface: "SATA III",
    formFactor: "3.5\"",
    readSpeedMbps: 180,
    writeSpeedMbps: 180,
    tags: ["storage"],
  },
];
