import type { Motherboard, RAM, PSU, Storage, Case } from "@/lib/types/components";

const mbDefaults = {
  pcieX16Slots: 1 as const,
  cpuPowerConnectors: ["8-pin"] as string[],
  atxPowerConnector: "24-pin",
};

export const motherboardBatch4: Motherboard[] = [
  {
    id: "mb-msi-b650-gaming-plus",
    name: "MSI B650 Gaming Plus WiFi",
    brand: "MSI",
    model: "B650 Gaming Plus WiFi",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 100, usedMax: 140, newMin: 150, newMax: 180 },
    socket: "AM5",
    chipset: "B650",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 192,
    maxRamSpeedMhz: 6400,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 4,
    fanHeaders: 4,
    argbHeaders: 2,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: true,
    wifiIncluded: true,
    bluetoothIncluded: true,
    specsSummary: "Top AM5 board in reseller listings.",
    tags: ["am5", "wifi", "popular"],
    ...mbDefaults,
  },
  {
    id: "mb-asus-b650m-k",
    name: "ASUS PRIME B650M-K",
    brand: "ASUS",
    model: "PRIME B650M-K",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 70, usedMax: 100, newMin: 100, newMax: 130 },
    socket: "AM5",
    chipset: "B650",
    formFactor: "Micro-ATX",
    ramType: "DDR5",
    ramSlots: 2,
    maxRamGb: 96,
    maxRamSpeedMhz: 6000,
    m2Slots: 1,
    m2Interfaces: ["NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 4,
    fanHeaders: 2,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 1,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Budget AM5 matx. Pairs with 7500F/9600X builds.",
    tags: ["am5", "matx", "budget"],
    ...mbDefaults,
  },
  {
    id: "mb-msi-z790-p",
    name: "MSI PRO Z790-P WiFi",
    brand: "MSI",
    model: "PRO Z790-P WiFi",
    category: "motherboard",
    performanceTier: "high",
    pricing: { usedMin: 140, usedMax: 190, newMin: 180, newMax: 220 },
    socket: "LGA1700",
    chipset: "Z790",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 192,
    maxRamSpeedMhz: 7200,
    m2Slots: 3,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieGen: 5,
    fanHeaders: 5,
    argbHeaders: 2,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 2,
    usbCFrontHeader: true,
    wifiIncluded: true,
    bluetoothIncluded: true,
    specsSummary: "Intel 12-14th gen Z790 staple.",
    tags: ["intel", "z790", "wifi"],
    ...mbDefaults,
  },
  {
    id: "mb-asus-b760m-a",
    name: "ASUS PRIME B760M-A D4",
    brand: "ASUS",
    model: "PRIME B760M-A D4",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 60, usedMax: 90, newMin: 90, newMax: 120 },
    socket: "LGA1700",
    chipset: "B760",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 5333,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 4,
    fanHeaders: 3,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "DDR4 Intel budget board — very common.",
    tags: ["intel", "ddr4", "budget"],
    ...mbDefaults,
  },
];

export const ramBatch4: RAM[] = [
  {
    id: "ram-ddr5-32gb-6000",
    name: "32GB DDR5-6000 (2x16GB)",
    brand: "G.Skill",
    model: "Trident Z5 32GB DDR5-6000",
    category: "ram",
    performanceTier: "mid",
    pricing: { usedMin: 80, usedMax: 110, newMin: 100, newMax: 130 },
    type: "DDR5",
    capacityGb: 32,
    speedMhz: 6000,
    modules: 2,
    rgb: true,
    tags: ["ddr5", "popular", "am5"],
  },
  {
    id: "ram-ddr5-16gb-5600",
    name: "16GB DDR5-5600 (2x8GB)",
    brand: "Corsair",
    model: "Vengeance 16GB DDR5-5600",
    category: "ram",
    performanceTier: "budget",
    pricing: { usedMin: 35, usedMax: 50, newMin: 45, newMax: 65 },
    type: "DDR5",
    capacityGb: 16,
    speedMhz: 5600,
    modules: 2,
    rgb: false,
    tags: ["ddr5", "budget"],
  },
  {
    id: "ram-ddr5-64gb-6000",
    name: "64GB DDR5-6000 (2x32GB)",
    brand: "Kingston",
    model: "Fury Beast 64GB DDR5-6000",
    category: "ram",
    performanceTier: "high",
    pricing: { usedMin: 150, usedMax: 200, newMin: 180, newMax: 240 },
    type: "DDR5",
    capacityGb: 64,
    speedMhz: 6000,
    modules: 2,
    rgb: false,
    tags: ["ddr5", "productivity"],
  },
];

export const psuBatch4: PSU[] = [
  {
    id: "psu-corsair-rm750e",
    name: "Corsair RM750e 750W Gold",
    brand: "Corsair",
    model: "RM750e",
    category: "psu",
    performanceTier: "mid",
    pricing: { usedMin: 55, usedMax: 80, newMin: 90, newMax: 110 },
    wattage: 750,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin"],
    sataConnectors: 8,
    epsConnectors: 2,
    tags: ["gold", "popular"],
  },
  {
    id: "psu-corsair-rm850e",
    name: "Corsair RM850e 850W Gold",
    brand: "Corsair",
    model: "RM850e",
    category: "psu",
    performanceTier: "high",
    pricing: { usedMin: 70, usedMax: 100, newMin: 110, newMax: 140 },
    wattage: 850,
    efficiency: "Gold",
    modular: "fully-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin", "4+4-pin"],
    pcieConnectors: ["6+2-pin", "6+2-pin", "6+2-pin"],
    sataConnectors: 8,
    epsConnectors: 2,
    tags: ["gold", "high-wattage"],
  },
  {
    id: "psu-evga-600w",
    name: "EVGA 600W 80+ Bronze",
    brand: "EVGA",
    model: "600 BR",
    category: "psu",
    performanceTier: "budget",
    pricing: { usedMin: 25, usedMax: 40, newMin: 0, newMax: 0 },
    wattage: 600,
    efficiency: "Bronze",
    modular: "non-modular",
    formFactor: "ATX",
    cpuConnectors: ["4+4-pin"],
    pcieConnectors: ["6+2-pin"],
    sataConnectors: 6,
    epsConnectors: 1,
    tags: ["budget", "bronze"],
  },
];

export const storageBatch4: Storage[] = [
  {
    id: "storage-samsung-990-pro-2tb",
    name: "Samsung 990 PRO 2TB NVMe",
    brand: "Samsung",
    model: "990 PRO 2TB",
    category: "storage",
    performanceTier: "enthusiast",
    pricing: { usedMin: 120, usedMax: 160, newMin: 150, newMax: 190 },
    type: "NVMe",
    capacityGb: 2000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 7450,
    writeSpeedMbps: 6900,
    tags: ["nvme", "fast", "popular"],
  },
  {
    id: "storage-wd-sn770-1tb",
    name: "WD Black SN770 1TB NVMe",
    brand: "Western Digital",
    model: "SN770 1TB",
    category: "storage",
    performanceTier: "mid",
    pricing: { usedMin: 45, usedMax: 65, newMin: 55, newMax: 75 },
    type: "NVMe",
    capacityGb: 1000,
    interface: "NVMe PCIe 4.0",
    formFactor: "M.2",
    readSpeedMbps: 5150,
    writeSpeedMbps: 4900,
    tags: ["nvme", "popular"],
  },
];

export const caseBatch4: Case[] = [
  {
    id: "case-nzxt-h5-flow",
    name: "NZXT H5 Flow",
    brand: "NZXT",
    model: "H5 Flow",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 50, usedMax: 75, newMin: 80, newMax: 100 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 365,
    maxCpuCoolerHeightMm: 165,
    driveBays25: 2,
    driveBays35: 1,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    supportedRadiatorSizesMm: [240, 280, 360],
    psuFormFactor: ["ATX"],
    tags: ["atx", "airflow", "popular"],
  },
  {
    id: "case-montech-xr",
    name: "Montech XR",
    brand: "Montech",
    model: "XR",
    category: "case",
    performanceTier: "budget",
    pricing: { usedMin: 35, usedMax: 55, newMin: 60, newMax: 80 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 380,
    maxCpuCoolerHeightMm: 170,
    driveBays25: 2,
    driveBays35: 2,
    includedFans: 3,
    fanSizesSupported: [120],
    supportedRadiatorSizesMm: [240, 360],
    psuFormFactor: ["ATX"],
    tags: ["budget", "rgb"],
  },
];
