import type { Cooler } from "@/lib/types/components";

export const coolerBatch3: Cooler[] = [
  {
    id: "cooler-noctua-u12s",
    name: "Noctua NH-U12S",
    brand: "Noctua",
    model: "NH-U12S",
    category: "cooler",
    performanceTier: "mid",
    pricing: { usedMin: 35, usedMax: 55, newMin: 70, newMax: 90 },
    type: "air",
    supportedSockets: ["AM4", "AM5", "LGA1200", "LGA1700"],
    tdpRatingWatts: 150,
    heightMm: 158,
    rgb: false,
    specsSummary: "Premium air cooler. Quiet and reliable flip upgrade.",
    tags: ["quiet", "premium"],
  },
  {
    id: "cooler-deepcool-ak620",
    name: "DeepCool AK620",
    brand: "DeepCool",
    model: "AK620",
    category: "cooler",
    performanceTier: "mid",
    pricing: { usedMin: 30, usedMax: 45, newMin: 55, newMax: 70 },
    type: "air",
    supportedSockets: ["AM4", "AM5", "LGA1200", "LGA1700"],
    tdpRatingWatts: 260,
    heightMm: 160,
    rgb: false,
    specsSummary: "Dual-tower budget king. Handles i7/Ryzen 7 well.",
    tags: ["value", "dual-tower"],
  },
  {
    id: "cooler-corsair-h100i",
    name: "Corsair iCUE H100i ELITE",
    brand: "Corsair",
    model: "iCUE H100i ELITE",
    category: "cooler",
    performanceTier: "high",
    pricing: { usedMin: 60, usedMax: 90, newMin: 120, newMax: 150 },
    type: "aio",
    supportedSockets: ["AM4", "AM5", "LGA1200", "LGA1700"],
    tdpRatingWatts: 250,
    radiatorSizeMm: 240,
    rgb: true,
    specsSummary: "240mm AIO with RGB pump. Popular in gaming flips.",
    tags: ["aio", "rgb"],
  },
  {
    id: "cooler-arctic-liquid-freezer-360",
    name: "Arctic Liquid Freezer II 360",
    brand: "Arctic",
    model: "Liquid Freezer II 360",
    category: "cooler",
    performanceTier: "high",
    pricing: { usedMin: 70, usedMax: 100, newMin: 120, newMax: 150 },
    type: "aio",
    supportedSockets: ["AM4", "AM5", "LGA1200", "LGA1700"],
    tdpRatingWatts: 300,
    radiatorSizeMm: 360,
    rgb: false,
    specsSummary: "Best-value 360mm AIO. Great for i9/Ryzen 9 flips.",
    tags: ["aio", "360mm", "value"],
  },
];
