import type { Cooler } from "@/lib/types/components";

export const coolerExtended: Cooler[] = [
  {
    id: "cooler-deepcool-ak400",
    name: "Deepcool AK400",
    brand: "Deepcool",
    model: "AK400",
    category: "cooler",
    performanceTier: "budget",
    pricing: { usedMin: 18, usedMax: 30, newMin: 35, newMax: 45 },
    type: "air",
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200"],
    heightMm: 155,
    tdpRatingWatts: 220,
    rgb: false,
    specsSummary: "Best budget tower cooler. Easy resale upgrade.",
    tags: ["budget", "popular"],
  },
  {
    id: "cooler-deepcool-ls520",
    name: "Deepcool LS520 240mm AIO",
    brand: "Deepcool",
    model: "LS520",
    category: "cooler",
    performanceTier: "mid",
    pricing: { usedMin: 45, usedMax: 70, newMin: 80, newMax: 100 },
    type: "aio",
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200"],
    radiatorSizeMm: 240,
    tdpRatingWatts: 250,
    rgb: true,
    specsSummary: "Budget AIO. 'Liquid cooled' keyword in listings.",
    tags: ["aio", "liquid"],
  },
  {
    id: "cooler-arctic-liquid-freezer-280",
    name: "Arctic Liquid Freezer II 280",
    brand: "Arctic",
    model: "Liquid Freezer II 280",
    category: "cooler",
    performanceTier: "high",
    pricing: { usedMin: 60, usedMax: 90, newMin: 100, newMax: 120 },
    type: "aio",
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200"],
    radiatorSizeMm: 280,
    tdpRatingWatts: 300,
    rgb: false,
    specsSummary: "Top-value AIO. Strong cooling per dollar.",
    tags: ["aio", "performance"],
  },
  {
    id: "cooler-stock-intel",
    name: "Intel Stock Cooler (LGA1700)",
    brand: "Intel",
    model: "Stock LGA1700 Cooler",
    category: "cooler",
    performanceTier: "entry",
    pricing: { usedMin: 0, usedMax: 5, newMin: 0, newMax: 0 },
    type: "air",
    supportedSockets: ["LGA1700"],
    heightMm: 45,
    tdpRatingWatts: 65,
    rgb: false,
    specsSummary: "Basic Intel stock cooler. Upgrade for resale appeal.",
    tags: ["stock", "weak"],
  },
];
