import type { Cooler } from "@/lib/types/components";

export const cpuCoolers: Cooler[] = [
  {
    id: "cooler-stock-amd",
    name: "AMD Wraith Stealth (Stock)",
    brand: "AMD",
    model: "Wraith Stealth",
    category: "cooler",
    performanceTier: "entry",
    pricing: { usedMin: 0, usedMax: 5, newMin: 0, newMax: 0 },
    type: "air",
    supportedSockets: ["AM4"],
    heightMm: 54,
    tdpRatingWatts: 65,
    rgb: false,
    tags: ["stock", "basic"],
  },
  {
    id: "cooler-hyper-212",
    name: "Cooler Master Hyper 212",
    brand: "Cooler Master",
    model: "Hyper 212 Black Edition",
    category: "cooler",
    performanceTier: "budget",
    pricing: { usedMin: 20, usedMax: 35, newMin: 40, newMax: 50 },
    type: "air",
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200"],
    heightMm: 159,
    tdpRatingWatts: 150,
    rgb: false,
    tags: ["popular", "budget"],
  },
  {
    id: "cooler-nh-d15",
    name: "Noctua NH-D15",
    brand: "Noctua",
    model: "NH-D15",
    category: "cooler",
    performanceTier: "high",
    pricing: { usedMin: 60, usedMax: 85, newMin: 100, newMax: 110 },
    type: "air",
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200"],
    heightMm: 165,
    tdpRatingWatts: 250,
    rgb: false,
    tags: ["premium", "quiet"],
  },
  {
    id: "cooler-aio-240",
    name: "240mm AIO Liquid Cooler",
    brand: "Corsair",
    model: "H100i RGB PRO XT",
    category: "cooler",
    performanceTier: "mid",
    pricing: { usedMin: 50, usedMax: 80, newMin: 100, newMax: 130 },
    type: "aio",
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200"],
    radiatorSizeMm: 240,
    tdpRatingWatts: 250,
    rgb: true,
    tags: ["aio", "liquid"],
  },
  {
    id: "cooler-aio-360",
    name: "360mm AIO Liquid Cooler",
    brand: "NZXT",
    model: "Kraken X73",
    category: "cooler",
    performanceTier: "high",
    pricing: { usedMin: 80, usedMax: 120, newMin: 150, newMax: 200 },
    type: "aio",
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200"],
    radiatorSizeMm: 360,
    tdpRatingWatts: 300,
    rgb: true,
    tags: ["aio", "high-end"],
  },
];
