import type { CPU } from "@/lib/types/components";

/** Additional AMD Ryzen CPUs commonly seen in reseller listings */
export const amdRyzenExtended: CPU[] = [
  {
    id: "cpu-ryzen-3-3100",
    name: "AMD Ryzen 3 3100",
    brand: "AMD",
    model: "Ryzen 3 3100",
    category: "cpu",
    performanceTier: "entry",
    pricing: { usedMin: 25, usedMax: 40, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    socket: "AM4",
    cores: 4,
    threads: 8,
    baseClockGhz: 3.6,
    boostClockGhz: 3.9,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["A320", "B450", "B550", "X470", "X570"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "Budget quad-core AM4. Common in office PCs and ultra-budget flips.",
    tags: ["budget", "office"],
  },
  {
    id: "cpu-ryzen-5-5500",
    name: "AMD Ryzen 5 5500",
    brand: "AMD",
    model: "Ryzen 5 5500",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 55, usedMax: 75, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "AM4",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.6,
    boostClockGhz: 4.2,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B450", "B550", "X470", "X570"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "Strong budget 6-core. Great value in used prebuilts.",
    tags: ["budget", "gaming"],
  },
  {
    id: "cpu-ryzen-5-5600g",
    name: "AMD Ryzen 5 5600G",
    brand: "AMD",
    model: "Ryzen 5 5600G",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 70, usedMax: 95, newMin: 0, newMax: 0 },
    releaseYear: 2021,
    socket: "AM4",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.9,
    boostClockGhz: 4.4,
    tdpWatts: 65,
    integratedGraphics: true,
    chipsetCompatibility: ["A520", "B450", "B550", "X570"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "APU with Vega graphics. Popular in budget builds without GPU.",
    tags: ["apu", "budget", "office"],
  },
  {
    id: "cpu-ryzen-7-5700",
    name: "AMD Ryzen 7 5700",
    brand: "AMD",
    model: "Ryzen 7 5700",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 110, usedMax: 145, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "AM4",
    cores: 8,
    threads: 16,
    baseClockGhz: 3.7,
    boostClockGhz: 4.6,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B450", "B550", "X470", "X570"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "OEM 8-core AM4. Common in prebuilt flips — not the 5700X.",
    tags: ["gaming", "oem"],
  },
  {
    id: "cpu-ryzen-7-5700x",
    name: "AMD Ryzen 7 5700X",
    brand: "AMD",
    model: "Ryzen 7 5700X",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 120, usedMax: 155, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "AM4",
    cores: 8,
    threads: 16,
    baseClockGhz: 3.4,
    boostClockGhz: 4.6,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B450", "B550", "X470", "X570"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "Efficient 8-core AM4. Excellent for productivity flips.",
    tags: ["productivity", "gaming"],
  },
  {
    id: "cpu-ryzen-7-5800x",
    name: "AMD Ryzen 7 5800X",
    brand: "AMD",
    model: "Ryzen 7 5800X",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 130, usedMax: 170, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    socket: "AM4",
    cores: 8,
    threads: 16,
    baseClockGhz: 3.8,
    boostClockGhz: 4.7,
    tdpWatts: 105,
    integratedGraphics: false,
    chipsetCompatibility: ["B450", "B550", "X470", "X570"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "High-clocked 8-core. Still desirable for gaming builds.",
    tags: ["gaming", "high-fps"],
  },
  {
    id: "cpu-ryzen-9-5900x",
    name: "AMD Ryzen 9 5900X",
    brand: "AMD",
    model: "Ryzen 9 5900X",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 180, usedMax: 240, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    socket: "AM4",
    cores: 12,
    threads: 24,
    baseClockGhz: 3.7,
    boostClockGhz: 4.8,
    tdpWatts: 105,
    integratedGraphics: false,
    chipsetCompatibility: ["B550", "X570"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "12-core flagship AM4. Strong resale for workstation builds.",
    tags: ["workstation", "productivity"],
  },
  {
    id: "cpu-ryzen-5-7600x",
    name: "AMD Ryzen 5 7600X",
    brand: "AMD",
    model: "Ryzen 5 7600X",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 150, usedMax: 190, newMin: 200, newMax: 230 },
    releaseYear: 2022,
    socket: "AM5",
    cores: 6,
    threads: 12,
    baseClockGhz: 4.7,
    boostClockGhz: 5.3,
    tdpWatts: 105,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Fast AM5 gaming CPU. Needs DDR5 + B650 board.",
    tags: ["am5", "gaming"],
  },
  {
    id: "cpu-ryzen-7-7700x",
    name: "AMD Ryzen 7 7700X",
    brand: "AMD",
    model: "Ryzen 7 7700X",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 220, usedMax: 280, newMin: 300, newMax: 350 },
    releaseYear: 2022,
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 4.5,
    boostClockGhz: 5.4,
    tdpWatts: 105,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "8-core AM5. Premium gaming and streaming builds.",
    tags: ["am5", "high-end"],
  },
  {
    id: "cpu-ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    model: "Ryzen 7 7800X3D",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 280, usedMax: 340, newMin: 350, newMax: 400 },
    releaseYear: 2023,
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 4.2,
    boostClockGhz: 5.0,
    tdpWatts: 120,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Best gaming CPU on AM5. Huge resale appeal.",
    tags: ["gaming", "3d-vcache", "am5"],
  },
];
