import type { CPU } from "@/lib/types/components";

export const cpuBatch4: CPU[] = [
  {
    id: "cpu-i5-14600k",
    name: "Intel Core i5-14600K",
    brand: "Intel",
    model: "Core i5-14600K",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 200, usedMax: 260, newMin: 250, newMax: 300 },
    releaseYear: 2023,
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    baseClockGhz: 3.5,
    boostClockGhz: 5.3,
    tdpWatts: 125,
    integratedGraphics: true,
    chipsetCompatibility: ["B760", "Z790", "Z690"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "14th gen Intel mid-high. Common in prebuilts.",
    tags: ["intel", "gaming"],
  },
  {
    id: "cpu-i7-14700k",
    name: "Intel Core i7-14700K",
    brand: "Intel",
    model: "Core i7-14700K",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 300, usedMax: 380, newMin: 350, newMax: 420 },
    releaseYear: 2023,
    socket: "LGA1700",
    cores: 20,
    threads: 28,
    baseClockGhz: 3.4,
    boostClockGhz: 5.6,
    tdpWatts: 125,
    integratedGraphics: true,
    chipsetCompatibility: ["B760", "Z790", "Z690"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "High-end 14th gen Intel flip CPU.",
    tags: ["intel", "high-end"],
  },
  {
    id: "cpu-i5-12400f",
    name: "Intel Core i5-12400F",
    brand: "Intel",
    model: "Core i5-12400F",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 90, usedMax: 120, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "LGA1700",
    cores: 6,
    threads: 12,
    baseClockGhz: 2.5,
    boostClockGhz: 4.4,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B660", "B760", "H610", "Z690", "Z790"],
    pcieGen: 4,
    ddrGeneration: "DDR4|DDR5",
    specsSummary: "Most flipped Intel CPU. Verify F vs non-F.",
    tags: ["popular", "budget", "intel"],
  },
  {
    id: "cpu-i5-13400f",
    name: "Intel Core i5-13400F",
    brand: "Intel",
    model: "Core i5-13400F",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 120, usedMax: 160, newMin: 0, newMax: 0 },
    releaseYear: 2023,
    socket: "LGA1700",
    cores: 10,
    threads: 16,
    baseClockGhz: 2.5,
    boostClockGhz: 4.6,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B660", "B760", "H610", "Z690", "Z790"],
    pcieGen: 4,
    ddrGeneration: "DDR4|DDR5",
    specsSummary: "13th gen budget Intel staple.",
    tags: ["popular", "intel"],
  },
  {
    id: "cpu-ultra-7-265k",
    name: "Intel Core Ultra 7 265K",
    brand: "Intel",
    model: "Core Ultra 7 265K",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 350, usedMax: 450, newMin: 400, newMax: 500 },
    releaseYear: 2024,
    socket: "LGA1851",
    cores: 20,
    threads: 20,
    baseClockGhz: 3.9,
    boostClockGhz: 5.5,
    tdpWatts: 125,
    integratedGraphics: true,
    chipsetCompatibility: ["Z890", "B860"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Arrow Lake Ultra 7. New platform flips.",
    tags: ["intel", "arrow-lake"],
  },
  {
    id: "cpu-ryzen-5-7500f",
    name: "AMD Ryzen 5 7500F",
    brand: "AMD",
    model: "Ryzen 5 7500F",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 120, usedMax: 160, newMin: 150, newMax: 180 },
    releaseYear: 2023,
    socket: "AM5",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.7,
    boostClockGhz: 5.0,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E", "X870", "X870E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Budget AM5 no-iGPU. Great flip CPU.",
    tags: ["am5", "budget"],
  },
];
