import type { CPU } from "@/lib/types/components";

/** High-volume reseller CPUs — batch 2 */
export const cpuBatch2: CPU[] = [
  {
    id: "cpu-ryzen-3-3300x",
    name: "AMD Ryzen 3 3300X",
    brand: "AMD",
    model: "Ryzen 3 3300X",
    category: "cpu",
    performanceTier: "entry",
    pricing: { usedMin: 35, usedMax: 55, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    socket: "AM4",
    cores: 4,
    threads: 8,
    baseClockGhz: 3.8,
    boostClockGhz: 4.3,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B450", "B550", "X470", "X570"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "Fast quad-core AM4. Still flips well as ultra-budget gaming.",
    tags: ["budget", "am4"],
  },
  {
    id: "cpu-ryzen-5-1600",
    name: "AMD Ryzen 5 1600",
    brand: "AMD",
    model: "Ryzen 5 1600",
    category: "cpu",
    performanceTier: "entry",
    pricing: { usedMin: 20, usedMax: 35, newMin: 0, newMax: 0 },
    releaseYear: 2017,
    socket: "AM4",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.2,
    boostClockGhz: 3.6,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["A320", "B350", "B450", "X370", "X470"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "Classic budget 6-core. Very common in old office/gaming PCs.",
    tags: ["budget", "legacy"],
  },
  {
    id: "cpu-ryzen-5-4500",
    name: "AMD Ryzen 5 4500",
    brand: "AMD",
    model: "Ryzen 5 4500",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 40, usedMax: 60, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "AM4",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.6,
    boostClockGhz: 4.1,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B450", "B550", "A520"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "OEM-style 6-core. Shows up in cheap prebuilt flips.",
    tags: ["budget", "oem"],
  },
  {
    id: "cpu-ryzen-7-2700x",
    name: "AMD Ryzen 7 2700X",
    brand: "AMD",
    model: "Ryzen 7 2700X",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 45, usedMax: 70, newMin: 0, newMax: 0 },
    releaseYear: 2018,
    socket: "AM4",
    cores: 8,
    threads: 16,
    baseClockGhz: 3.7,
    boostClockGhz: 4.3,
    tdpWatts: 105,
    integratedGraphics: false,
    chipsetCompatibility: ["B450", "B350", "X470", "X370"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "8-core Zen+. Cheap workstation flip CPU.",
    tags: ["productivity", "legacy"],
  },
  {
    id: "cpu-ryzen-9-3950x",
    name: "AMD Ryzen 9 3950X",
    brand: "AMD",
    model: "Ryzen 9 3950X",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 200, usedMax: 280, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    socket: "AM4",
    cores: 16,
    threads: 32,
    baseClockGhz: 3.5,
    boostClockGhz: 4.7,
    tdpWatts: 105,
    integratedGraphics: false,
    chipsetCompatibility: ["X570", "B550", "X470"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "16-core AM4 workstation chip. Strong creator resale.",
    tags: ["workstation", "productivity"],
  },
  {
    id: "cpu-ryzen-5-8600g",
    name: "AMD Ryzen 5 8600G",
    brand: "AMD",
    model: "Ryzen 5 8600G",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 140, usedMax: 180, newMin: 200, newMax: 230 },
    releaseYear: 2024,
    socket: "AM5",
    cores: 6,
    threads: 12,
    baseClockGhz: 4.3,
    boostClockGhz: 5.0,
    tdpWatts: 65,
    integratedGraphics: true,
    chipsetCompatibility: ["A620", "B650", "B650E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "APU with RDNA3 graphics. Great for GPU-less office flips.",
    tags: ["apu", "am5"],
  },
  {
    id: "cpu-ryzen-9-7900x",
    name: "AMD Ryzen 9 7900X",
    brand: "AMD",
    model: "Ryzen 9 7900X",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 300, usedMax: 380, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "AM5",
    cores: 12,
    threads: 24,
    baseClockGhz: 4.7,
    boostClockGhz: 5.6,
    tdpWatts: 170,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "12-core AM5 flagship (non-3D). High-end flip potential.",
    tags: ["am5", "workstation"],
  },
  {
    id: "cpu-ryzen-9-7950x3d",
    name: "AMD Ryzen 9 7950X3D",
    brand: "AMD",
    model: "Ryzen 9 7950X3D",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 450, usedMax: 550, newMin: 0, newMax: 0 },
    releaseYear: 2023,
    socket: "AM5",
    cores: 16,
    threads: 32,
    baseClockGhz: 4.2,
    boostClockGhz: 5.7,
    tdpWatts: 120,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Top-tier AM5 gaming + productivity CPU.",
    tags: ["3d-vcache", "enthusiast", "am5"],
  },
  {
    id: "cpu-i3-10100",
    name: "Intel Core i3-10100",
    brand: "Intel",
    model: "Core i3-10100",
    category: "cpu",
    performanceTier: "entry",
    pricing: { usedMin: 35, usedMax: 55, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    socket: "LGA1200",
    cores: 4,
    threads: 8,
    baseClockGhz: 3.6,
    boostClockGhz: 4.3,
    tdpWatts: 65,
    integratedGraphics: true,
    chipsetCompatibility: ["H410", "B460", "H510", "B560"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "Office/student quad-core. Extremely common in Dell/HP PCs.",
    tags: ["office", "lga1200", "prebuilt"],
  },
  {
    id: "cpu-i3-12100f",
    name: "Intel Core i3-12100F",
    brand: "Intel",
    model: "Core i3-12100F",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 55, usedMax: 75, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "LGA1700",
    cores: 4,
    threads: 8,
    baseClockGhz: 3.3,
    boostClockGhz: 4.3,
    tdpWatts: 58,
    integratedGraphics: false,
    chipsetCompatibility: ["H610", "B660", "B760"],
    pcieGen: 5,
    ddrGeneration: "DDR4|DDR5",
    specsSummary: "Budget Alder Lake quad. Surprisingly capable for cheap builds.",
    tags: ["budget", "lga1700"],
  },
  {
    id: "cpu-i5-9400f",
    name: "Intel Core i5-9400F",
    brand: "Intel",
    model: "Core i5-9400F",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 35, usedMax: 55, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    socket: "LGA1151",
    cores: 6,
    threads: 6,
    baseClockGhz: 2.9,
    boostClockGhz: 4.1,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B360", "B365", "H310", "Z390"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "Legacy 9th-gen 6-core. Still appears in cheap used gaming PCs.",
    tags: ["legacy", "lga1151"],
  },
  {
    id: "cpu-i5-9600k",
    name: "Intel Core i5-9600K",
    brand: "Intel",
    model: "Core i5-9600K",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 50, usedMax: 75, newMin: 0, newMax: 0 },
    releaseYear: 2018,
    socket: "LGA1151",
    cores: 6,
    threads: 6,
    baseClockGhz: 3.7,
    boostClockGhz: 4.6,
    tdpWatts: 95,
    integratedGraphics: true,
    chipsetCompatibility: ["Z390", "Z370", "B365"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "Overclockable 9th-gen. Common in older gaming builds.",
    tags: ["gaming", "lga1151"],
  },
  {
    id: "cpu-i5-14400f",
    name: "Intel Core i5-14400F",
    brand: "Intel",
    model: "Core i5-14400F",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 140, usedMax: 180, newMin: 200, newMax: 230 },
    releaseYear: 2024,
    socket: "LGA1700",
    cores: 10,
    threads: 16,
    baseClockGhz: 2.5,
    boostClockGhz: 4.7,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B760", "Z790", "H610"],
    pcieGen: 5,
    ddrGeneration: "DDR4|DDR5",
    specsSummary: "Current-gen 10-core. Good for newer Intel flips.",
    tags: ["lga1700", "modern"],
  },
  {
    id: "cpu-i5-14600k",
    name: "Intel Core i5-14600K",
    brand: "Intel",
    model: "Core i5-14600K",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 200, usedMax: 260, newMin: 280, newMax: 320 },
    releaseYear: 2023,
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    baseClockGhz: 3.5,
    boostClockGhz: 5.3,
    tdpWatts: 125,
    integratedGraphics: true,
    chipsetCompatibility: ["B760", "Z790", "Z690"],
    pcieGen: 5,
    ddrGeneration: "DDR4|DDR5",
    specsSummary: "14-core hybrid Raptor Lake refresh. Strong gaming CPU.",
    tags: ["gaming", "lga1700"],
  },
  {
    id: "cpu-i7-8700",
    name: "Intel Core i7-8700",
    brand: "Intel",
    model: "Core i7-8700",
    category: "cpu",
    performanceTier: "budget",
    pricing: { usedMin: 50, usedMax: 80, newMin: 0, newMax: 0 },
    releaseYear: 2017,
    socket: "LGA1151",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.2,
    boostClockGhz: 4.6,
    tdpWatts: 65,
    integratedGraphics: true,
    chipsetCompatibility: ["Z370", "B360", "H310"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "8th-gen 6-core with HT. Common in older prebuilts.",
    tags: ["legacy", "lga1151"],
  },
  {
    id: "cpu-i7-9700k",
    name: "Intel Core i7-9700K",
    brand: "Intel",
    model: "Core i7-9700K",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 80, usedMax: 120, newMin: 0, newMax: 0 },
    releaseYear: 2018,
    socket: "LGA1151",
    cores: 8,
    threads: 8,
    baseClockGhz: 3.6,
    boostClockGhz: 4.9,
    tdpWatts: 95,
    integratedGraphics: true,
    chipsetCompatibility: ["Z390", "Z370"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "8-core 9th-gen. Still sells in budget gaming flips.",
    tags: ["gaming", "lga1151"],
  },
  {
    id: "cpu-i7-11700f",
    name: "Intel Core i7-11700F",
    brand: "Intel",
    model: "Core i7-11700F",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 100, usedMax: 140, newMin: 0, newMax: 0 },
    releaseYear: 2021,
    socket: "LGA1200",
    cores: 8,
    threads: 16,
    baseClockGhz: 2.5,
    boostClockGhz: 4.9,
    tdpWatts: 65,
    integratedGraphics: false,
    chipsetCompatibility: ["B560", "Z590", "H510"],
    pcieGen: 4,
    ddrGeneration: "DDR4",
    specsSummary: "11th-gen 8-core. Often bundled with B560 boards.",
    tags: ["lga1200", "gaming"],
  },
  {
    id: "cpu-i9-9900k",
    name: "Intel Core i9-9900K",
    brand: "Intel",
    model: "Core i9-9900K",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 120, usedMax: 170, newMin: 0, newMax: 0 },
    releaseYear: 2018,
    socket: "LGA1151",
    cores: 8,
    threads: 16,
    baseClockGhz: 3.6,
    boostClockGhz: 5.0,
    tdpWatts: 95,
    integratedGraphics: true,
    chipsetCompatibility: ["Z390"],
    pcieGen: 3,
    ddrGeneration: "DDR4",
    specsSummary: "Flagship 9th-gen. Needs Z390 and decent cooler.",
    tags: ["gaming", "lga1151"],
  },
  {
    id: "cpu-i9-13900k",
    name: "Intel Core i9-13900K",
    brand: "Intel",
    model: "Core i9-13900K",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 320, usedMax: 400, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    socket: "LGA1700",
    cores: 24,
    threads: 32,
    baseClockGhz: 3.0,
    boostClockGhz: 5.8,
    tdpWatts: 125,
    integratedGraphics: true,
    chipsetCompatibility: ["Z690", "Z790"],
    pcieGen: 5,
    ddrGeneration: "DDR4|DDR5",
    specsSummary: "24-core Raptor Lake. Premium flip — verify thermals.",
    tags: ["enthusiast", "lga1700"],
  },
];
