import type { CPU } from "@/lib/types/components";

/** AMD Zen 5 AM5 CPUs */
export const zen5CPUs: CPU[] = [
  {
    id: "cpu-ryzen-9-9950x3d",
    name: "AMD Ryzen 9 9950X3D",
    brand: "AMD",
    model: "Ryzen 9 9950X3D",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 550, usedMax: 650, newMin: 650, newMax: 750 },
    releaseYear: 2025,
    socket: "AM5",
    cores: 16,
    threads: 32,
    baseClockGhz: 4.3,
    boostClockGhz: 5.7,
    tdpWatts: 170,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E", "X870", "X870E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Zen 5 flagship with 3D V-Cache. Top gaming CPU.",
    tags: ["gaming", "3d-vcache", "am5", "flagship"],
  },
  {
    id: "cpu-ryzen-7-9800x3d",
    name: "AMD Ryzen 7 9800X3D",
    brand: "AMD",
    model: "Ryzen 7 9800X3D",
    category: "cpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 400, usedMax: 500, newMin: 480, newMax: 550 },
    releaseYear: 2024,
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 4.7,
    boostClockGhz: 5.2,
    tdpWatts: 120,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E", "X870", "X870E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Best gaming CPU in most builds. Huge flip demand.",
    tags: ["gaming", "3d-vcache", "am5"],
  },
  {
    id: "cpu-ryzen-7-9700x",
    name: "AMD Ryzen 7 9700X",
    brand: "AMD",
    model: "Ryzen 7 9700X",
    category: "cpu",
    performanceTier: "high",
    pricing: { usedMin: 250, usedMax: 320, newMin: 300, newMax: 360 },
    releaseYear: 2024,
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 3.8,
    boostClockGhz: 5.5,
    tdpWatts: 65,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E", "X870", "X870E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Efficient Zen 5 8-core. Strong mid-high builds.",
    tags: ["am5", "efficient"],
  },
  {
    id: "cpu-ryzen-5-9600x",
    name: "AMD Ryzen 5 9600X",
    brand: "AMD",
    model: "Ryzen 5 9600X",
    category: "cpu",
    performanceTier: "mid",
    pricing: { usedMin: 170, usedMax: 220, newMin: 200, newMax: 250 },
    releaseYear: 2024,
    socket: "AM5",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.9,
    boostClockGhz: 5.4,
    tdpWatts: 65,
    integratedGraphics: true,
    chipsetCompatibility: ["B650", "B650E", "X670", "X670E", "X870", "X870E"],
    pcieGen: 5,
    ddrGeneration: "DDR5",
    specsSummary: "Budget Zen 5. Great value gaming CPU.",
    tags: ["am5", "budget", "gaming"],
  },
];
