import type { Motherboard } from "@/lib/types/components";

const mbDefaults = {
  pcieX16Slots: 1 as const,
  cpuPowerConnectors: ["8-pin"] as string[],
  atxPowerConnector: "24-pin",
};

/** LGA1200 + additional AM4/AM5 boards — batch 2 */
export const motherboardBatch2: Motherboard[] = [
  {
    id: "mb-msi-b460m-pro-vdh",
    name: "MSI B460M PRO-VDH",
    brand: "MSI",
    model: "B460M PRO-VDH",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 40, usedMax: 65, newMin: 0, newMax: 0 },
    socket: "LGA1200",
    chipset: "B460",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 2933,
    m2Slots: 1,
    m2Interfaces: ["NVMe PCIe 3.0"],
    sataPorts: 4,
    pcieGen: 3,
    fanHeaders: 2,
    argbHeaders: 0,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Pairs with i5-10400F in tons of prebuilts.",
    tags: ["lga1200", "matx", "prebuilt"],
    ...mbDefaults,
  },
  {
    id: "mb-asus-prime-b560m-a",
    name: "ASUS PRIME B560M-A",
    brand: "ASUS",
    model: "PRIME B560M-A",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 50, usedMax: 75, newMin: 0, newMax: 0 },
    socket: "LGA1200",
    chipset: "B560",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 5000,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 3.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieGen: 4,
    fanHeaders: 3,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "11th-gen Intel budget board. Memory OC on B560.",
    tags: ["lga1200", "matx"],
    ...mbDefaults,
  },
  {
    id: "mb-asrock-b450m-pro4",
    name: "ASRock B450M Pro4",
    brand: "ASRock",
    model: "B450M Pro4",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 40, usedMax: 65, newMin: 0, newMax: 0 },
    socket: "AM4",
    chipset: "B450",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 3533,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 3.0", "NVMe PCIe 3.0"],
    sataPorts: 4,
    pcieGen: 3,
    fanHeaders: 3,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Top AM4 budget board. Flash BIOS for Ryzen 5000.",
    tags: ["am4", "b450", "popular"],
    ...mbDefaults,
  },
  {
    id: "mb-msi-b550-a-pro",
    name: "MSI B550-A PRO",
    brand: "MSI",
    model: "B550-A PRO",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 65, usedMax: 90, newMin: 0, newMax: 0 },
    socket: "AM4",
    chipset: "B550",
    formFactor: "ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 4400,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 3.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieGen: 4,
    fanHeaders: 4,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Clean ATX B550. PCIe 4.0 for GPU and primary M.2.",
    tags: ["am4", "atx"],
    ...mbDefaults,
  },
  {
    id: "mb-msi-x570-a-pro",
    name: "MSI X570-A PRO",
    brand: "MSI",
    model: "X570-A PRO",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 80, usedMax: 110, newMin: 0, newMax: 0 },
    socket: "AM4",
    chipset: "X570",
    formFactor: "ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 4400,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieGen: 4,
    fanHeaders: 4,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Entry X570. Chipset fan — check noise in resale.",
    tags: ["am4", "x570"],
    ...mbDefaults,
  },
  {
    id: "mb-gigabyte-b650-aorus-elite",
    name: "Gigabyte B650 AORUS ELITE AX",
    brand: "Gigabyte",
    model: "B650 AORUS ELITE AX",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 120, usedMax: 160, newMin: 180, newMax: 210 },
    socket: "AM5",
    chipset: "B650",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 6666,
    m2Slots: 3,
    m2Interfaces: ["NVMe PCIe 5.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 5,
    fanHeaders: 4,
    argbHeaders: 3,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 2,
    usbCFrontHeader: true,
    wifiIncluded: true,
    bluetoothIncluded: true,
    specsSummary: "Popular AM5 board with WiFi 6E and PCIe 5.0 M.2.",
    tags: ["am5", "wifi", "atx"],
    ...mbDefaults,
  },
  {
    id: "mb-asus-tuf-z690-plus",
    name: "ASUS TUF Gaming Z690-PLUS WIFI D4",
    brand: "ASUS",
    model: "TUF Gaming Z690-PLUS WIFI D4",
    category: "motherboard",
    performanceTier: "high",
    pricing: { usedMin: 130, usedMax: 180, newMin: 0, newMax: 0 },
    socket: "LGA1700",
    chipset: "Z690",
    formFactor: "ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 5333,
    m2Slots: 3,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 5,
    fanHeaders: 4,
    argbHeaders: 3,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 2,
    usbCFrontHeader: true,
    wifiIncluded: true,
    bluetoothIncluded: true,
    specsSummary: "DDR4 Z690 with OC support. Good for 12th/13th gen flips.",
    tags: ["intel", "z690", "ddr4"],
    ...mbDefaults,
  },
];
