import type { Motherboard } from "@/lib/types/components";

const mbDefaults = {
  pcieX16Slots: 1 as const,
  cpuPowerConnectors: ["8-pin"] as string[],
  atxPowerConnector: "24-pin",
};

export const motherboardExtended: Motherboard[] = [
  {
    id: "mb-msi-b550m-pro-vdh-wifi",
    name: "MSI B550M PRO-VDH WIFI",
    brand: "MSI",
    model: "B550M PRO-VDH WIFI",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 55, usedMax: 80, newMin: 100, newMax: 120 },
    socket: "AM4",
    chipset: "B550",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 4400,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 3.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 4,
    fanHeaders: 3,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: true,
    bluetoothIncluded: true,
    specsSummary: "Extremely common AM4 matx board in reseller listings.",
    tags: ["am4", "matx", "wifi", "popular"],
    ...mbDefaults,
  },
  {
    id: "mb-asus-tuf-b550-plus",
    name: "ASUS TUF Gaming B550-PLUS",
    brand: "ASUS",
    model: "TUF Gaming B550-PLUS",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 70, usedMax: 100, newMin: 0, newMax: 0 },
    socket: "AM4",
    chipset: "B550",
    formFactor: "ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 4866,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 3.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieGen: 4,
    fanHeaders: 4,
    argbHeaders: 2,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Reliable ATX B550. Good upgrade path for Ryzen 5000.",
    tags: ["am4", "atx", "gaming"],
    ...mbDefaults,
  },
  {
    id: "mb-asrock-b650m-pro-rs",
    name: "ASRock B650M Pro RS",
    brand: "ASRock",
    model: "B650M Pro RS",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 90, usedMax: 120, newMin: 130, newMax: 160 },
    socket: "AM5",
    chipset: "B650",
    formFactor: "Micro-ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 7200,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 5,
    fanHeaders: 3,
    argbHeaders: 2,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: true,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Budget AM5 DDR5 board. Common in new-gen flips.",
    tags: ["am5", "ddr5", "matx"],
    ...mbDefaults,
  },
  {
    id: "mb-msi-pro-b760m-p",
    name: "MSI PRO B760M-P DDR4",
    brand: "MSI",
    model: "PRO B760M-P DDR4",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 70, usedMax: 95, newMin: 110, newMax: 130 },
    socket: "LGA1700",
    chipset: "B760",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 5333,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieGen: 5,
    fanHeaders: 3,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Budget Intel 12th/13th/14th gen DDR4 platform.",
    tags: ["intel", "lga1700", "ddr4"],
    ...mbDefaults,
  },
  {
    id: "mb-asus-prime-h610m-a",
    name: "ASUS PRIME H610M-A D4",
    brand: "ASUS",
    model: "PRIME H610M-A D4",
    category: "motherboard",
    performanceTier: "entry",
    pricing: { usedMin: 45, usedMax: 70, newMin: 80, newMax: 100 },
    socket: "LGA1700",
    chipset: "H610",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 2,
    maxRamGb: 64,
    maxRamSpeedMhz: 3200,
    m2Slots: 1,
    m2Interfaces: ["NVMe PCIe 3.0"],
    sataPorts: 4,
    pcieGen: 4,
    fanHeaders: 2,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 1,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Ultra-budget Intel board. Limited upgradeability.",
    tags: ["intel", "budget", "office"],
    ...mbDefaults,
  },
  {
    id: "mb-msi-z790-p-wifi",
    name: "MSI PRO Z790-P WIFI",
    brand: "MSI",
    model: "PRO Z790-P WIFI",
    category: "motherboard",
    performanceTier: "high",
    pricing: { usedMin: 140, usedMax: 190, newMin: 220, newMax: 260 },
    socket: "LGA1700",
    chipset: "Z790",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 192,
    maxRamSpeedMhz: 7000,
    m2Slots: 4,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieGen: 5,
    fanHeaders: 5,
    argbHeaders: 2,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 2,
    usbCFrontHeader: true,
    wifiIncluded: true,
    bluetoothIncluded: true,
    specsSummary: "Premium Intel platform with WiFi and 4 M.2 slots.",
    tags: ["intel", "z790", "high-end"],
    ...mbDefaults,
  },
  {
    id: "mb-gigabyte-b450m-ds3h",
    name: "Gigabyte B450M DS3H",
    brand: "Gigabyte",
    model: "B450M DS3H",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 35, usedMax: 55, newMin: 0, newMax: 0 },
    socket: "AM4",
    chipset: "B450",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 3600,
    m2Slots: 1,
    m2Interfaces: ["NVMe PCIe 3.0"],
    sataPorts: 4,
    pcieGen: 3,
    fanHeaders: 2,
    argbHeaders: 0,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    wifiIncluded: false,
    bluetoothIncluded: false,
    specsSummary: "Cheapest AM4 boards. Verify BIOS for Ryzen 5000.",
    tags: ["am4", "budget", "matx"],
    ...mbDefaults,
  },
];
