import type { Motherboard } from "@/lib/types/components";

export const am4Motherboards: Motherboard[] = [
  {
    id: "mb-b550-aorus-elite",
    name: "Gigabyte B550 AORUS Elite",
    brand: "Gigabyte",
    model: "B550 AORUS Elite",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 60, usedMax: 90, newMin: 120, newMax: 150 },
    socket: "AM4",
    chipset: "B550",
    formFactor: "ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 4733,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 3.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieX16Slots: 1,
    pcieGen: 4,
    fanHeaders: 4,
    argbHeaders: 2,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    cpuPowerConnectors: ["8-pin"],
    atxPowerConnector: "24-pin",
    wifiIncluded: false,
    bluetoothIncluded: false,
    tags: ["popular", "b550"],
  },
  {
    id: "mb-b450-tomahawk",
    name: "MSI B450 Tomahawk MAX",
    brand: "MSI",
    model: "B450 Tomahawk MAX",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 50, usedMax: 75, newMin: 0, newMax: 0 },
    socket: "AM4",
    chipset: "B450",
    formFactor: "ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 4133,
    m2Slots: 1,
    m2Interfaces: ["NVMe PCIe 3.0"],
    sataPorts: 6,
    pcieX16Slots: 1,
    pcieGen: 3,
    fanHeaders: 4,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    cpuPowerConnectors: ["8-pin"],
    atxPowerConnector: "24-pin",
    wifiIncluded: false,
    bluetoothIncluded: false,
    tags: ["budget"],
  },
  {
    id: "mb-b550m-pro-vdh",
    name: "MSI B550M PRO-VDH WIFI",
    brand: "MSI",
    model: "B550M PRO-VDH WIFI",
    category: "motherboard",
    performanceTier: "budget",
    pricing: { usedMin: 55, usedMax: 80, newMin: 100, newMax: 120 },
    socket: "AM4",
    chipset: "B550",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 4400,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 3.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieX16Slots: 1,
    pcieGen: 4,
    fanHeaders: 3,
    argbHeaders: 1,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    cpuPowerConnectors: ["8-pin"],
    atxPowerConnector: "24-pin",
    wifiIncluded: true,
    bluetoothIncluded: true,
    tags: ["matx", "wifi"],
  },
];

export const am5Motherboards: Motherboard[] = [
  {
    id: "mb-b650-aorus-elite",
    name: "Gigabyte B650 AORUS Elite AX",
    brand: "Gigabyte",
    model: "B650 AORUS Elite AX",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 120, usedMax: 160, newMin: 180, newMax: 220 },
    socket: "AM5",
    chipset: "B650",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 6400,
    m2Slots: 3,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieX16Slots: 1,
    pcieGen: 5,
    fanHeaders: 4,
    argbHeaders: 3,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: true,
    cpuPowerConnectors: ["8-pin"],
    atxPowerConnector: "24-pin",
    wifiIncluded: true,
    bluetoothIncluded: true,
    tags: ["am5", "wifi"],
  },
];

export const intelMotherboards: Motherboard[] = [
  {
    id: "mb-b760m-a",
    name: "ASUS PRIME B760M-A",
    brand: "ASUS",
    model: "PRIME B760M-A",
    category: "motherboard",
    performanceTier: "mid",
    pricing: { usedMin: 80, usedMax: 110, newMin: 130, newMax: 160 },
    socket: "LGA1700",
    chipset: "B760",
    formFactor: "Micro-ATX",
    ramType: "DDR4",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 5066,
    m2Slots: 2,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 4,
    pcieX16Slots: 1,
    pcieGen: 5,
    fanHeaders: 3,
    argbHeaders: 2,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 1,
    usbCFrontHeader: false,
    cpuPowerConnectors: ["8-pin"],
    atxPowerConnector: "24-pin",
    wifiIncluded: false,
    bluetoothIncluded: false,
    tags: ["intel", "lga1700"],
  },
  {
    id: "mb-z690-a",
    name: "ASUS PRIME Z690-A",
    brand: "ASUS",
    model: "PRIME Z690-A",
    category: "motherboard",
    performanceTier: "high",
    pricing: { usedMin: 140, usedMax: 190, newMin: 0, newMax: 0 },
    socket: "LGA1700",
    chipset: "Z690",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamGb: 128,
    maxRamSpeedMhz: 6000,
    m2Slots: 4,
    m2Interfaces: ["NVMe PCIe 4.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0", "NVMe PCIe 4.0"],
    sataPorts: 6,
    pcieX16Slots: 2,
    pcieGen: 5,
    fanHeaders: 5,
    argbHeaders: 3,
    rgbHeaders: 0,
    usb2Headers: 2,
    usb3Headers: 2,
    usbCFrontHeader: true,
    cpuPowerConnectors: ["8-pin"],
    atxPowerConnector: "24-pin",
    wifiIncluded: true,
    bluetoothIncluded: true,
    tags: ["overclocking", "high-end"],
  },
];
