import type { GPU } from "@/lib/types/components";

export const amdGpuExtended: GPU[] = [
  {
    id: "gpu-rx-5500-xt",
    name: "AMD Radeon RX 5500 XT 8GB",
    brand: "AMD",
    model: "RX 5500 XT 8GB",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 60, usedMax: 90, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "Navi 14",
    vramGb: 8,
    tdpWatts: 130,
    lengthMm: 225,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    specsSummary: "Budget AMD card. Common in entry prebuilts.",
    tags: ["budget", "1080p-entry"],
  },
  {
    id: "gpu-rx-5700-xt",
    name: "AMD Radeon RX 5700 XT",
    brand: "AMD",
    model: "RX 5700 XT",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 120, usedMax: 160, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "Navi 10",
    vramGb: 8,
    tdpWatts: 225,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 600,
    specsSummary: "Popular used card. Check hotspot temps and paste.",
    tags: ["1080p", "1440p-entry", "mining-risk"],
  },
  {
    id: "gpu-rx-6650-xt",
    name: "AMD Radeon RX 6650 XT",
    brand: "AMD",
    model: "RX 6650 XT",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 160, usedMax: 200, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "Navi 23",
    vramGb: 8,
    tdpWatts: 176,
    lengthMm: 240,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    specsSummary: "Refresh 6600 XT. Efficient 1080p high-refresh gaming.",
    tags: ["1080p", "efficient"],
  },
  {
    id: "gpu-rx-6750-xt",
    name: "AMD Radeon RX 6750 XT",
    brand: "AMD",
    model: "RX 6750 XT",
    category: "gpu",
    performanceTier: "upper-mid",
    pricing: { usedMin: 240, usedMax: 300, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "Navi 22",
    vramGb: 12,
    tdpWatts: 250,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    specsSummary: "12GB VRAM. Strong 1440p value in used market.",
    tags: ["1440p"],
  },
  {
    id: "gpu-rx-6800",
    name: "AMD Radeon RX 6800",
    brand: "AMD",
    model: "RX 6800",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 280, usedMax: 350, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "Navi 21",
    vramGb: 16,
    tdpWatts: 250,
    lengthMm: 267,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    specsSummary: "16GB RDNA2. Great for high-VRAM workloads.",
    tags: ["1440p", "workstation"],
  },
  {
    id: "gpu-rx-6800-xt",
    name: "AMD Radeon RX 6800 XT",
    brand: "AMD",
    model: "RX 6800 XT",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 320, usedMax: 400, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "Navi 21",
    vramGb: 16,
    tdpWatts: 300,
    lengthMm: 287,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 750,
    specsSummary: "Competes with 3080. Premium flip if condition is good.",
    tags: ["1440p", "4k-entry"],
  },
  {
    id: "gpu-rx-7800-xt",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    model: "RX 7800 XT",
    category: "gpu",
    performanceTier: "upper-mid",
    pricing: { usedMin: 380, usedMax: 450, newMin: 480, newMax: 530 },
    releaseYear: 2023,
    chipset: "Navi 32",
    vramGb: 16,
    tdpWatts: 263,
    lengthMm: 267,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 700,
    specsSummary: "Modern 1440p sweet spot. 16GB VRAM appeals to buyers.",
    tags: ["1440p", "modern"],
  },
  {
    id: "gpu-rx-7900-gre",
    name: "AMD Radeon RX 7900 GRE",
    brand: "AMD",
    model: "RX 7900 GRE",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 480, usedMax: 560, newMin: 0, newMax: 0 },
    releaseYear: 2024,
    chipset: "Navi 31",
    vramGb: 16,
    tdpWatts: 260,
    lengthMm: 276,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 750,
    specsSummary: "High-end RDNA3. Strong 4K and creator appeal.",
    tags: ["4k", "high-end"],
  },
];
