import type { GPU } from "@/lib/types/components";

export const amdGPUs: GPU[] = [
  {
    id: "gpu-rx-6600",
    name: "AMD Radeon RX 6600",
    brand: "AMD",
    model: "RX 6600",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 140, usedMax: 180, newMin: 0, newMax: 0 },
    releaseYear: 2021,
    chipset: "Navi 23",
    vramGb: 8,
    tdpWatts: 132,
    lengthMm: 240,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    tags: ["1080p", "efficient"],
  },
  {
    id: "gpu-rx-6700-xt",
    name: "AMD Radeon RX 6700 XT",
    brand: "AMD",
    model: "RX 6700 XT",
    category: "gpu",
    performanceTier: "upper-mid",
    pricing: { usedMin: 220, usedMax: 280, newMin: 0, newMax: 0 },
    releaseYear: 2021,
    chipset: "Navi 22",
    vramGb: 12,
    tdpWatts: 230,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    tags: ["1440p"],
  },
  {
    id: "gpu-rx-580",
    name: "AMD Radeon RX 580 8GB",
    brand: "AMD",
    model: "RX 580 8GB",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 50, usedMax: 80, newMin: 0, newMax: 0 },
    releaseYear: 2017,
    chipset: "Polaris 20",
    vramGb: 8,
    tdpWatts: 185,
    lengthMm: 241,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    tags: ["budget", "older"],
  },
  {
    id: "gpu-rx-7600",
    name: "AMD Radeon RX 7600",
    brand: "AMD",
    model: "RX 7600",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 200, usedMax: 250, newMin: 260, newMax: 300 },
    releaseYear: 2023,
    chipset: "Navi 33",
    vramGb: 8,
    tdpWatts: 165,
    lengthMm: 204,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    tags: ["1080p", "1440p-entry"],
  },
];
