import type { GPU } from "@/lib/types/components";

/** Legacy + modern GPUs commonly listed on marketplace — batch 2 */
export const gpuBatch2: GPU[] = [
  {
    id: "gpu-gtx-1050-ti",
    name: "NVIDIA GeForce GTX 1050 Ti",
    brand: "NVIDIA",
    model: "GTX 1050 Ti",
    category: "gpu",
    performanceTier: "entry",
    pricing: { usedMin: 35, usedMax: 55, newMin: 0, newMax: 0 },
    releaseYear: 2016,
    chipset: "GP107",
    vramGb: 4,
    tdpWatts: 75,
    lengthMm: 191,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: [],
    minPsuWatts: 300,
    specsSummary: "No PCIe power needed. Ultra-budget flip staple.",
    tags: ["budget", "legacy", "low-power"],
  },
  {
    id: "gpu-gtx-1060-6gb",
    name: "NVIDIA GeForce GTX 1060 6GB",
    brand: "NVIDIA",
    model: "GTX 1060 6GB",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 45, usedMax: 70, newMin: 0, newMax: 0 },
    releaseYear: 2016,
    chipset: "GP106",
    vramGb: 6,
    tdpWatts: 120,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["6-pin"],
    minPsuWatts: 400,
    specsSummary: "Classic budget card. Verify 3GB vs 6GB in listings.",
    tags: ["budget", "legacy"],
  },
  {
    id: "gpu-gtx-1070",
    name: "NVIDIA GeForce GTX 1070",
    brand: "NVIDIA",
    model: "GTX 1070",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 70, usedMax: 100, newMin: 0, newMax: 0 },
    releaseYear: 2016,
    chipset: "GP104",
    vramGb: 8,
    tdpWatts: 150,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    specsSummary: "Older 1080p card. Watch for mining wear.",
    tags: ["1080p", "legacy", "mining-risk"],
  },
  {
    id: "gpu-gtx-1080",
    name: "NVIDIA GeForce GTX 1080",
    brand: "NVIDIA",
    model: "GTX 1080",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 90, usedMax: 130, newMin: 0, newMax: 0 },
    releaseYear: 2016,
    chipset: "GP104",
    vramGb: 8,
    tdpWatts: 180,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    specsSummary: "Pascal flagship. Still flips if thermals are good.",
    tags: ["1080p", "legacy"],
  },
  {
    id: "gpu-gtx-1650",
    name: "NVIDIA GeForce GTX 1650",
    brand: "NVIDIA",
    model: "GTX 1650",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 60, usedMax: 90, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU117",
    vramGb: 4,
    tdpWatts: 75,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: [],
    minPsuWatts: 300,
    specsSummary: "Low-power card. Common in Dell/HP small form factor PCs.",
    tags: ["budget", "low-power", "sff"],
  },
  {
    id: "gpu-gtx-1650-super",
    name: "NVIDIA GeForce GTX 1650 Super",
    brand: "NVIDIA",
    model: "GTX 1650 Super",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 70, usedMax: 100, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU116",
    vramGb: 4,
    tdpWatts: 100,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["6-pin"],
    minPsuWatts: 350,
    specsSummary: "Better than base 1650. Good budget 1080p option.",
    tags: ["budget", "1080p"],
  },
  {
    id: "gpu-gtx-1660-super",
    name: "NVIDIA GeForce GTX 1660 Super",
    brand: "NVIDIA",
    model: "GTX 1660 Super",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 80, usedMax: 110, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU116",
    vramGb: 6,
    tdpWatts: 125,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 450,
    specsSummary: "Very popular budget GPU. High flip volume.",
    tags: ["budget", "1080p", "popular"],
  },
  {
    id: "gpu-rtx-2060",
    name: "NVIDIA GeForce RTX 2060",
    brand: "NVIDIA",
    model: "RTX 2060",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 90, usedMax: 130, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU106",
    vramGb: 6,
    tdpWatts: 160,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    specsSummary: "Entry RTX with DLSS. Check 6GB vs 12GB variant.",
    tags: ["1080p", "ray-tracing"],
  },
  {
    id: "gpu-rtx-2060-super",
    name: "NVIDIA GeForce RTX 2060 Super",
    brand: "NVIDIA",
    model: "RTX 2060 Super",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 110, usedMax: 150, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU106",
    vramGb: 8,
    tdpWatts: 175,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    specsSummary: "8GB Turing card. Solid 1080p high-refresh gaming.",
    tags: ["1080p"],
  },
  {
    id: "gpu-rtx-2080",
    name: "NVIDIA GeForce RTX 2080",
    brand: "NVIDIA",
    model: "RTX 2080",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 130, usedMax: 180, newMin: 0, newMax: 0 },
    releaseYear: 2018,
    chipset: "TU104",
    vramGb: 8,
    tdpWatts: 215,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    specsSummary: "Older high-end Turing. Mining history common.",
    tags: ["1440p-entry", "mining-risk"],
  },
  {
    id: "gpu-rtx-3090",
    name: "NVIDIA GeForce RTX 3090",
    brand: "NVIDIA",
    model: "RTX 3090",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 550, usedMax: 700, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "GA102",
    vramGb: 24,
    tdpWatts: 350,
    lengthMm: 313,
    slotWidth: 3,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 750,
    specsSummary: "24GB flagship. Heavy mining use — inspect carefully.",
    tags: ["4k", "workstation", "mining-risk"],
  },
  {
    id: "gpu-rtx-4090",
    name: "NVIDIA GeForce RTX 4090",
    brand: "NVIDIA",
    model: "RTX 4090",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 1400, usedMax: 1700, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "AD102",
    vramGb: 24,
    tdpWatts: 450,
    lengthMm: 336,
    slotWidth: 3.5,
    pcieGen: 4,
    powerConnectors: ["12VHPWR"],
    minPsuWatts: 850,
    specsSummary: "Top consumer GPU. Verify adapter cable and case fit.",
    tags: ["4k", "enthusiast", "ai"],
  },
  {
    id: "gpu-rx-560",
    name: "AMD Radeon RX 560",
    brand: "AMD",
    model: "RX 560",
    category: "gpu",
    performanceTier: "entry",
    pricing: { usedMin: 25, usedMax: 45, newMin: 0, newMax: 0 },
    releaseYear: 2017,
    chipset: "Polaris 21",
    vramGb: 4,
    tdpWatts: 80,
    lengthMm: 170,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: [],
    minPsuWatts: 400,
    specsSummary: "Ultra-cheap GPU. Good for office PC flips.",
    tags: ["budget", "legacy"],
  },
  {
    id: "gpu-rx-570",
    name: "AMD Radeon RX 570 4GB",
    brand: "AMD",
    model: "RX 570 4GB",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 35, usedMax: 55, newMin: 0, newMax: 0 },
    releaseYear: 2017,
    chipset: "Polaris 20",
    vramGb: 4,
    tdpWatts: 150,
    lengthMm: 241,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["6-pin"],
    minPsuWatts: 450,
    specsSummary: "Classic budget AMD. Verify 4GB vs 8GB in listing.",
    tags: ["budget", "legacy"],
  },
  {
    id: "gpu-rx-590",
    name: "AMD Radeon RX 590",
    brand: "AMD",
    model: "RX 590",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 50, usedMax: 75, newMin: 0, newMax: 0 },
    releaseYear: 2018,
    chipset: "Polaris 30",
    vramGb: 8,
    tdpWatts: 225,
    lengthMm: 241,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    specsSummary: "Power-hungry Polaris refresh. Check PSU capacity.",
    tags: ["budget", "1080p-entry"],
  },
  {
    id: "gpu-rx-5600-xt",
    name: "AMD Radeon RX 5600 XT",
    brand: "AMD",
    model: "RX 5600 XT",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 80, usedMax: 110, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "Navi 10",
    vramGb: 6,
    tdpWatts: 150,
    lengthMm: 241,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    specsSummary: "Strong 1080p card. BIOS flash issues on some models.",
    tags: ["1080p"],
  },
  {
    id: "gpu-rx-6500-xt",
    name: "AMD Radeon RX 6500 XT",
    brand: "AMD",
    model: "RX 6500 XT",
    category: "gpu",
    performanceTier: "entry",
    pricing: { usedMin: 70, usedMax: 100, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "Navi 24",
    vramGb: 4,
    tdpWatts: 107,
    lengthMm: 190,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["6-pin"],
    minPsuWatts: 400,
    specsSummary: "PCIe x4 only — needs PCIe 4.0 motherboard for full speed.",
    tags: ["budget", "pcie-limit"],
  },
  {
    id: "gpu-rx-6900-xt",
    name: "AMD Radeon RX 6900 XT",
    brand: "AMD",
    model: "RX 6900 XT",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 400, usedMax: 500, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "Navi 21",
    vramGb: 16,
    tdpWatts: 300,
    lengthMm: 287,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 750,
    specsSummary: "16GB RDNA2 flagship. Premium flip tier.",
    tags: ["4k", "high-end"],
  },
  {
    id: "gpu-rx-7700-xt",
    name: "AMD Radeon RX 7700 XT",
    brand: "AMD",
    model: "RX 7700 XT",
    category: "gpu",
    performanceTier: "upper-mid",
    pricing: { usedMin: 320, usedMax: 380, newMin: 400, newMax: 450 },
    releaseYear: 2023,
    chipset: "Navi 32",
    vramGb: 12,
    tdpWatts: 245,
    lengthMm: 267,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 700,
    specsSummary: "12GB RDNA3. Strong 1440p modern gaming card.",
    tags: ["1440p", "modern"],
  },
  {
    id: "gpu-rx-7900-xtx",
    name: "AMD Radeon RX 7900 XTX",
    brand: "AMD",
    model: "RX 7900 XTX",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 650, usedMax: 800, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "Navi 31",
    vramGb: 24,
    tdpWatts: 355,
    lengthMm: 287,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 800,
    specsSummary: "24GB AMD flagship. Competes with RTX 4080.",
    tags: ["4k", "enthusiast"],
  },
  {
    id: "gpu-arc-a750",
    name: "Intel Arc A750",
    brand: "Intel",
    model: "Arc A750",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 120, usedMax: 160, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "ACM-G10",
    vramGb: 8,
    tdpWatts: 225,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    specsSummary: "Intel discrete GPU. Verify driver maturity for resale.",
    tags: ["intel-arc", "1080p"],
  },
  {
    id: "gpu-arc-a770",
    name: "Intel Arc A770 16GB",
    brand: "Intel",
    model: "Arc A770 16GB",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 180, usedMax: 230, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "ACM-G10",
    vramGb: 16,
    tdpWatts: 225,
    lengthMm: 267,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    specsSummary: "16GB Intel Arc. Good for AV1 encoding / light AI flips.",
    tags: ["intel-arc", "1440p-entry"],
  },
];
