import type { GPU } from "@/lib/types/components";

export const gpuBatch4: GPU[] = [
  {
    id: "gpu-rtx-4070-super",
    name: "NVIDIA GeForce RTX 4070 Super",
    brand: "NVIDIA",
    model: "RTX 4070 Super",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 480, usedMax: 580, newMin: 550, newMax: 650 },
    releaseYear: 2024,
    chipset: "AD104",
    vramGb: 12,
    tdpWatts: 220,
    lengthMm: 285,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 650,
    specsSummary: "Strong 1440p/4K entry. Very common in flips.",
    tags: ["1440p", "popular"],
  },
  {
    id: "gpu-rtx-4080-super",
    name: "NVIDIA GeForce RTX 4080 Super",
    brand: "NVIDIA",
    model: "RTX 4080 Super",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 750, usedMax: 950, newMin: 900, newMax: 1100 },
    releaseYear: 2024,
    chipset: "AD103",
    vramGb: 16,
    tdpWatts: 320,
    lengthMm: 304,
    slotWidth: 3,
    pcieGen: 4,
    powerConnectors: ["12VHPWR"],
    minPsuWatts: 850,
    specsSummary: "High-end Ada. Premium flip GPU.",
    tags: ["4k", "high-end"],
  },
  {
    id: "gpu-rtx-4060-ti-16gb",
    name: "NVIDIA GeForce RTX 4060 Ti 16GB",
    brand: "NVIDIA",
    model: "RTX 4060 Ti 16GB",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 320, usedMax: 400, newMin: 380, newMax: 450 },
    releaseYear: 2023,
    chipset: "AD106",
    vramGb: 16,
    tdpWatts: 165,
    lengthMm: 240,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    specsSummary: "16GB variant — verify VRAM in listings.",
    tags: ["1080p", "1440p-entry"],
  },
  {
    id: "gpu-rx-7700-xt",
    name: "AMD Radeon RX 7700 XT",
    brand: "AMD",
    model: "RX 7700 XT",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 320, usedMax: 400, newMin: 380, newMax: 450 },
    releaseYear: 2023,
    chipset: "Navi 32",
    vramGb: 12,
    tdpWatts: 245,
    lengthMm: 267,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 650,
    specsSummary: "AMD 1440p sweet spot.",
    tags: ["1440p", "amd"],
  },
  {
    id: "gpu-rx-7800-xt",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    model: "RX 7800 XT",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 380, usedMax: 480, newMin: 450, newMax: 520 },
    releaseYear: 2023,
    chipset: "Navi 32",
    vramGb: 16,
    tdpWatts: 263,
    lengthMm: 267,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 700,
    specsSummary: "Strong AMD mid-high GPU for flips.",
    tags: ["1440p", "amd"],
  },
  {
    id: "gpu-rx-7600",
    name: "AMD Radeon RX 7600",
    brand: "AMD",
    model: "RX 7600",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 180, usedMax: 240, newMin: 220, newMax: 280 },
    releaseYear: 2023,
    chipset: "Navi 33",
    vramGb: 8,
    tdpWatts: 165,
    lengthMm: 204,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    specsSummary: "Budget 1080p AMD card.",
    tags: ["1080p", "budget", "amd"],
  },
];
