import type { GPU } from "@/lib/types/components";

/** NVIDIA RTX 50-series (Blackwell) */
export const blackwellGPUs: GPU[] = [
  {
    id: "gpu-rtx-5090",
    name: "NVIDIA GeForce RTX 5090",
    brand: "NVIDIA",
    model: "RTX 5090",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 1400, usedMax: 1800, newMin: 1999, newMax: 2200 },
    releaseYear: 2025,
    chipset: "GB202",
    vramGb: 32,
    tdpWatts: 575,
    lengthMm: 304,
    slotWidth: 3,
    pcieGen: 5,
    powerConnectors: ["12VHPWR"],
    minPsuWatts: 1000,
    specsSummary: "Blackwell flagship. 4K ultra / creator workloads.",
    tags: ["4k", "flagship", "high-end"],
  },
  {
    id: "gpu-rtx-5080",
    name: "NVIDIA GeForce RTX 5080",
    brand: "NVIDIA",
    model: "RTX 5080",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 850, usedMax: 1100, newMin: 999, newMax: 1200 },
    releaseYear: 2025,
    chipset: "GB203",
    vramGb: 16,
    tdpWatts: 360,
    lengthMm: 304,
    slotWidth: 3,
    pcieGen: 5,
    powerConnectors: ["12VHPWR"],
    minPsuWatts: 850,
    specsSummary: "High-end Blackwell. Strong 4K gaming resale.",
    tags: ["4k", "1440p", "high-end"],
  },
  {
    id: "gpu-rtx-5070-ti",
    name: "NVIDIA GeForce RTX 5070 Ti",
    brand: "NVIDIA",
    model: "RTX 5070 Ti",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 650, usedMax: 800, newMin: 749, newMax: 850 },
    releaseYear: 2025,
    chipset: "GB203",
    vramGb: 16,
    tdpWatts: 300,
    lengthMm: 285,
    slotWidth: 2.5,
    pcieGen: 5,
    powerConnectors: ["12VHPWR"],
    minPsuWatts: 750,
    specsSummary: "Upper-mid Blackwell. Great flip GPU.",
    tags: ["1440p", "high-fps"],
  },
  {
    id: "gpu-rtx-5070",
    name: "NVIDIA GeForce RTX 5070",
    brand: "NVIDIA",
    model: "RTX 5070",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 500, usedMax: 650, newMin: 549, newMax: 650 },
    releaseYear: 2025,
    chipset: "GB205",
    vramGb: 12,
    tdpWatts: 250,
    lengthMm: 260,
    slotWidth: 2,
    pcieGen: 5,
    powerConnectors: ["12VHPWR"],
    minPsuWatts: 650,
    specsSummary: "Sweet-spot Blackwell for gaming PCs.",
    tags: ["1440p", "popular"],
  },
];
