import type { GPU } from "@/lib/types/components";

export const nvidiaExtended: GPU[] = [
  {
    id: "gpu-rtx-3050",
    name: "NVIDIA GeForce RTX 3050",
    brand: "NVIDIA",
    model: "RTX 3050",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 120, usedMax: 160, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "GA106",
    vramGb: 8,
    tdpWatts: 130,
    lengthMm: 235,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    specsSummary: "Entry RTX with DLSS. 1080p esports / light gaming.",
    tags: ["budget", "1080p"],
  },
  {
    id: "gpu-rtx-3070-ti",
    name: "NVIDIA GeForce RTX 3070 Ti",
    brand: "NVIDIA",
    model: "RTX 3070 Ti",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 300, usedMax: 380, newMin: 0, newMax: 0 },
    releaseYear: 2021,
    chipset: "GA104",
    vramGb: 8,
    tdpWatts: 290,
    lengthMm: 285,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    specsSummary: "Strong 1440p card. Higher power draw than 3070.",
    tags: ["1440p"],
  },
  {
    id: "gpu-rtx-3080",
    name: "NVIDIA GeForce RTX 3080 10GB",
    brand: "NVIDIA",
    model: "RTX 3080 10GB",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 350, usedMax: 430, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "GA102",
    vramGb: 10,
    tdpWatts: 320,
    lengthMm: 285,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 750,
    specsSummary: "Still a premium flip GPU. Verify thermals and mining history.",
    tags: ["1440p", "4k-entry"],
  },
  {
    id: "gpu-rtx-4060-ti-16gb",
    name: "NVIDIA GeForce RTX 4060 Ti 16GB",
    brand: "NVIDIA",
    model: "RTX 4060 Ti 16GB",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 320, usedMax: 380, newMin: 400, newMax: 450 },
    releaseYear: 2023,
    chipset: "AD106",
    vramGb: 16,
    tdpWatts: 165,
    lengthMm: 240,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    specsSummary: "16GB VRAM variant. Good for AI/light workstation flips.",
    tags: ["1080p", "1440p", "ai-entry"],
  },
  {
    id: "gpu-rtx-4070",
    name: "NVIDIA GeForce RTX 4070",
    brand: "NVIDIA",
    model: "RTX 4070",
    category: "gpu",
    performanceTier: "upper-mid",
    pricing: { usedMin: 420, usedMax: 500, newMin: 520, newMax: 580 },
    releaseYear: 2023,
    chipset: "AD104",
    vramGb: 12,
    tdpWatts: 200,
    lengthMm: 250,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 650,
    specsSummary: "Efficient 1440p/4K entry. High buyer demand.",
    tags: ["1440p", "efficient"],
  },
  {
    id: "gpu-rtx-4070-ti",
    name: "NVIDIA GeForce RTX 4070 Ti",
    brand: "NVIDIA",
    model: "RTX 4070 Ti",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 550, usedMax: 650, newMin: 0, newMax: 0 },
    releaseYear: 2023,
    chipset: "AD104",
    vramGb: 12,
    tdpWatts: 285,
    lengthMm: 285,
    slotWidth: 2.5,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 700,
    specsSummary: "High-end 1440p/4K gaming. Premium resale tier.",
    tags: ["1440p", "4k"],
  },
  {
    id: "gpu-rtx-4080",
    name: "NVIDIA GeForce RTX 4080",
    brand: "NVIDIA",
    model: "RTX 4080",
    category: "gpu",
    performanceTier: "enthusiast",
    pricing: { usedMin: 750, usedMax: 900, newMin: 0, newMax: 0 },
    releaseYear: 2022,
    chipset: "AD103",
    vramGb: 16,
    tdpWatts: 320,
    lengthMm: 304,
    slotWidth: 3,
    pcieGen: 4,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 750,
    specsSummary: "Enthusiast GPU. Check case clearance and PSU headroom.",
    tags: ["4k", "enthusiast"],
  },
  {
    id: "gpu-gtx-1660-ti",
    name: "NVIDIA GeForce GTX 1660 Ti",
    brand: "NVIDIA",
    model: "GTX 1660 Ti",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 70, usedMax: 100, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU116",
    vramGb: 6,
    tdpWatts: 120,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 450,
    specsSummary: "Older budget card. Still sells for ultra-cheap flips.",
    tags: ["budget", "older"],
  },
  {
    id: "gpu-rtx-2070-super",
    name: "NVIDIA GeForce RTX 2070 Super",
    brand: "NVIDIA",
    model: "RTX 2070 Super",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 140, usedMax: 180, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU104",
    vramGb: 8,
    tdpWatts: 215,
    lengthMm: 267,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin", "8-pin"],
    minPsuWatts: 650,
    specsSummary: "Turing-era 1440p card. Watch for mining wear.",
    tags: ["1080p", "1440p-entry"],
  },
];
