import type { GPU } from "@/lib/types/components";

export const nvidiaGPUs: GPU[] = [
  {
    id: "gpu-rtx-3060-12gb",
    name: "NVIDIA GeForce RTX 3060 12GB",
    brand: "NVIDIA",
    model: "RTX 3060 12GB",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 180, usedMax: 220, newMin: 0, newMax: 0 },
    releaseYear: 2021,
    chipset: "GA106",
    vramGb: 12,
    tdpWatts: 170,
    lengthMm: 242,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    tags: ["popular", "1080p", "1440p-entry"],
  },
  {
    id: "gpu-rtx-3060-ti",
    name: "NVIDIA GeForce RTX 3060 Ti",
    brand: "NVIDIA",
    model: "RTX 3060 Ti",
    category: "gpu",
    performanceTier: "upper-mid",
    pricing: { usedMin: 220, usedMax: 280, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "GA104",
    vramGb: 8,
    tdpWatts: 200,
    lengthMm: 242,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 600,
    tags: ["1440p"],
  },
  {
    id: "gpu-rtx-3070",
    name: "NVIDIA GeForce RTX 3070",
    brand: "NVIDIA",
    model: "RTX 3070",
    category: "gpu",
    performanceTier: "high",
    pricing: { usedMin: 280, usedMax: 350, newMin: 0, newMax: 0 },
    releaseYear: 2020,
    chipset: "GA104",
    vramGb: 8,
    tdpWatts: 220,
    lengthMm: 285,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 650,
    tags: ["1440p", "high-fps"],
  },
  {
    id: "gpu-rtx-4060",
    name: "NVIDIA GeForce RTX 4060",
    brand: "NVIDIA",
    model: "RTX 4060",
    category: "gpu",
    performanceTier: "mid",
    pricing: { usedMin: 250, usedMax: 300, newMin: 280, newMax: 320 },
    releaseYear: 2023,
    chipset: "AD107",
    vramGb: 8,
    tdpWatts: 115,
    lengthMm: 240,
    slotWidth: 2,
    pcieGen: 4,
    powerConnectors: ["8-pin"],
    minPsuWatts: 550,
    tags: ["efficient", "1080p"],
  },
  {
    id: "gpu-gtx-1660-super",
    name: "NVIDIA GeForce GTX 1660 Super",
    brand: "NVIDIA",
    model: "GTX 1660 Super",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 80, usedMax: 110, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU116",
    vramGb: 6,
    tdpWatts: 125,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 450,
    tags: ["budget", "1080p-entry"],
  },
  {
    id: "gpu-rtx-2060",
    name: "NVIDIA GeForce RTX 2060",
    brand: "NVIDIA",
    model: "RTX 2060",
    category: "gpu",
    performanceTier: "budget",
    pricing: { usedMin: 100, usedMax: 140, newMin: 0, newMax: 0 },
    releaseYear: 2019,
    chipset: "TU106",
    vramGb: 6,
    tdpWatts: 160,
    lengthMm: 229,
    slotWidth: 2,
    pcieGen: 3,
    powerConnectors: ["8-pin"],
    minPsuWatts: 500,
    tags: ["budget", "1080p"],
  },
];
