import type { Case } from "@/lib/types/components";

export const caseBatch3: Case[] = [
  {
    id: "case-corsair-4000d",
    name: "Corsair 4000D Airflow",
    brand: "Corsair",
    model: "4000D Airflow",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 50, usedMax: 75, newMin: 85, newMax: 105 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 360,
    maxCpuCoolerHeightMm: 170,
    supportedRadiatorSizesMm: [120, 240, 280, 360],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 180,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 2,
    specsSummary: "Extremely popular mid-tower. Clean look for listings.",
    tags: ["popular", "airflow"],
  },
  {
    id: "case-fractal-torrent",
    name: "Fractal Design Torrent",
    brand: "Fractal Design",
    model: "Torrent",
    category: "case",
    performanceTier: "high",
    pricing: { usedMin: 100, usedMax: 140, newMin: 0, newMax: 0 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 461,
    maxCpuCoolerHeightMm: 188,
    supportedRadiatorSizesMm: [120, 140, 240, 280, 360, 420],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 200,
    includedFans: 2,
    fanSizesSupported: [120, 140, 180],
    driveBays25: 4,
    driveBays35: 2,
    specsSummary: "Premium airflow case with 180mm fans.",
    tags: ["premium", "airflow"],
  },
  {
    id: "case-nzxt-h510",
    name: "NZXT H510",
    brand: "NZXT",
    model: "H510",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 40, usedMax: 65, newMin: 0, newMax: 0 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 381,
    maxCpuCoolerHeightMm: 165,
    supportedRadiatorSizesMm: [120, 240, 280],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 180,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 2,
    specsSummary: "Classic NZXT aesthetic. Limited airflow — note in listings.",
    tags: ["aesthetic", "older"],
  },
  {
    id: "case-cooler-master-mesh",
    name: "Cooler Master MasterBox TD500",
    brand: "Cooler Master",
    model: "MasterBox TD500 Mesh",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 45, usedMax: 70, newMin: 80, newMax: 100 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 410,
    maxCpuCoolerHeightMm: 165,
    supportedRadiatorSizesMm: [120, 240, 360],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 180,
    includedFans: 3,
    fanSizesSupported: [120],
    driveBays25: 2,
    driveBays35: 2,
    specsSummary: "Mesh front + included RGB fans. Good budget gaming case.",
    tags: ["rgb", "gaming"],
  },
];
