import type { Case } from "@/lib/types/components";

export const caseExtended: Case[] = [
  {
    id: "case-lian-li-o11",
    name: "Lian Li O11 Dynamic",
    brand: "Lian Li",
    model: "O11 Dynamic",
    category: "case",
    performanceTier: "high",
    pricing: { usedMin: 80, usedMax: 120, newMin: 0, newMax: 0 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 420,
    maxCpuCoolerHeightMm: 155,
    supportedRadiatorSizesMm: [120, 240, 280, 360],
    psuFormFactor: ["ATX", "SFX"],
    maxPsuLengthMm: 200,
    includedFans: 0,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 2,
    specsSummary: "Showcase case. High resale appeal with good airflow setup.",
    tags: ["showcase", "popular"],
  },
  {
    id: "case-nzxt-h7-flow",
    name: "NZXT H7 Flow",
    brand: "NZXT",
    model: "H7 Flow",
    category: "case",
    performanceTier: "high",
    pricing: { usedMin: 90, usedMax: 130, newMin: 150, newMax: 180 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 400,
    maxCpuCoolerHeightMm: 185,
    supportedRadiatorSizesMm: [120, 140, 240, 280, 360],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 180,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 2,
    specsSummary: "Premium airflow case. Clean aesthetic for listings.",
    tags: ["airflow", "premium"],
  },
  {
    id: "case-fractal-north",
    name: "Fractal Design North",
    brand: "Fractal Design",
    model: "North",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 70, usedMax: 100, newMin: 120, newMax: 140 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 355,
    maxCpuCoolerHeightMm: 170,
    supportedRadiatorSizesMm: [120, 240, 280, 360],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 170,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 1,
    specsSummary: "Wood-accent aesthetic. Stands out in Facebook listings.",
    tags: ["aesthetic", "popular"],
  },
  {
    id: "case-cooler-master-q300l",
    name: "Cooler Master Q300L",
    brand: "Cooler Master",
    model: "MasterBox Q300L",
    category: "case",
    performanceTier: "budget",
    pricing: { usedMin: 25, usedMax: 45, newMin: 50, newMax: 65 },
    supportedFormFactors: ["Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 360,
    maxCpuCoolerHeightMm: 157,
    supportedRadiatorSizesMm: [120, 240],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 160,
    includedFans: 1,
    fanSizesSupported: [120],
    driveBays25: 2,
    driveBays35: 1,
    specsSummary: "Ultra-budget matx case. Common in cheap flips.",
    tags: ["budget", "matx"],
  },
];
