import type { Case } from "@/lib/types/components";

export const pcCases: Case[] = [
  {
    id: "case-nzxt-h510",
    name: "NZXT H510",
    brand: "NZXT",
    model: "H510",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 35, usedMax: 55, newMin: 60, newMax: 80 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 381,
    maxCpuCoolerHeightMm: 165,
    supportedRadiatorSizesMm: [120, 240, 280],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 180,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 2,
    tags: ["popular", "clean"],
  },
  {
    id: "case-fractal-meshify-c",
    name: "Fractal Design Meshify C",
    brand: "Fractal Design",
    model: "Meshify C",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 40, usedMax: 65, newMin: 70, newMax: 95 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 315,
    maxCpuCoolerHeightMm: 172,
    supportedRadiatorSizesMm: [120, 240, 280, 360],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 175,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 2,
    tags: ["airflow"],
  },
  {
    id: "case-corsair-4000d",
    name: "Corsair 4000D Airflow",
    brand: "Corsair",
    model: "4000D Airflow",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 45, usedMax: 70, newMin: 80, newMax: 100 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 360,
    maxCpuCoolerHeightMm: 170,
    supportedRadiatorSizesMm: [120, 240, 280, 360],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 180,
    includedFans: 2,
    fanSizesSupported: [120, 140],
    driveBays25: 2,
    driveBays35: 2,
    tags: ["airflow", "popular"],
  },
  {
    id: "case-cooler-master-n200",
    name: "Cooler Master NR200",
    brand: "Cooler Master",
    model: "NR200",
    category: "case",
    performanceTier: "mid",
    pricing: { usedMin: 50, usedMax: 75, newMin: 85, newMax: 100 },
    supportedFormFactors: ["Mini-ITX"],
    maxGpuLengthMm: 330,
    maxCpuCoolerHeightMm: 155,
    supportedRadiatorSizesMm: [120, 240, 280],
    psuFormFactor: ["ATX", "SFX"],
    maxPsuLengthMm: 130,
    includedFans: 2,
    fanSizesSupported: [92, 120, 140],
    driveBays25: 2,
    driveBays35: 0,
    tags: ["sff", "itx"],
  },
  {
    id: "case-budget-atx",
    name: "Budget ATX Case",
    brand: "Generic",
    model: "Budget ATX Mid Tower",
    category: "case",
    performanceTier: "budget",
    pricing: { usedMin: 15, usedMax: 30, newMin: 35, newMax: 50 },
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 300,
    maxCpuCoolerHeightMm: 155,
    supportedRadiatorSizesMm: [120, 240],
    psuFormFactor: ["ATX"],
    maxPsuLengthMm: 160,
    includedFans: 1,
    fanSizesSupported: [120],
    driveBays25: 2,
    driveBays35: 2,
    tags: ["budget"],
  },
];
