import type { Fans, WiFiModule } from "@/lib/types/components";

export const fansBatch3: Fans[] = [
  {
    id: "fans-arctic-p12-5pack",
    name: "120mm PWM Fans (5-Pack)",
    brand: "Arctic",
    model: "P12 PWM PST 5-Pack",
    category: "fans",
    performanceTier: "budget",
    pricing: { usedMin: 25, usedMax: 40, newMin: 35, newMax: 50 },
    sizeMm: 120,
    quantity: 5,
    rgb: false,
    argb: false,
    pwm: true,
    specsSummary: "Value pack for case upgrades. Quiet and reliable.",
    tags: ["value", "upgrade"],
  },
  {
    id: "fans-noctua-nf-a12x25",
    name: "120mm Premium Fan (Single)",
    brand: "Noctua",
    model: "NF-A12x25 PWM",
    category: "fans",
    performanceTier: "high",
    pricing: { usedMin: 20, usedMax: 30, newMin: 35, newMax: 45 },
    sizeMm: 120,
    quantity: 1,
    rgb: false,
    argb: false,
    pwm: true,
    specsSummary: "Premium airflow fan. Adds polish to high-end flips.",
    tags: ["premium", "quiet"],
  },
  {
    id: "fans-lian-li-uni-120-3pack",
    name: "120mm ARGB Fans (3-Pack)",
    brand: "Lian Li",
    model: "UNI Fan SL120 3-Pack",
    category: "fans",
    performanceTier: "high",
    pricing: { usedMin: 50, usedMax: 75, newMin: 90, newMax: 110 },
    sizeMm: 120,
    quantity: 3,
    rgb: false,
    argb: true,
    pwm: true,
    specsSummary: "Daisy-chain RGB fans. Popular in showcase builds.",
    tags: ["rgb", "showcase"],
  },
  {
    id: "fans-corsair-ql120-3pack",
    name: "120mm RGB Fans (3-Pack)",
    brand: "Corsair",
    model: "iCUE QL120 3-Pack",
    category: "fans",
    performanceTier: "high",
    pricing: { usedMin: 60, usedMax: 90, newMin: 100, newMax: 130 },
    sizeMm: 120,
    quantity: 3,
    rgb: true,
    argb: false,
    pwm: true,
    specsSummary: "Dual-ring RGB. Verify controller compatibility.",
    tags: ["rgb", "premium"],
  },
  {
    id: "fans-140mm-2pack",
    name: "140mm PWM Fans (2-Pack)",
    brand: "be quiet!",
    model: "Silent Wings 4 140mm 2-Pack",
    category: "fans",
    performanceTier: "mid",
    pricing: { usedMin: 30, usedMax: 45, newMin: 50, newMax: 65 },
    sizeMm: 140,
    quantity: 2,
    rgb: false,
    argb: false,
    pwm: true,
    specsSummary: "140mm fans for NZXT H7 / Fractal cases.",
    tags: ["140mm", "quiet"],
  },
];

export const wifiBatch3: WiFiModule[] = [
  {
    id: "wifi-realtek-rtl8822ce",
    name: "Realtek RTL8822CE WiFi 5",
    brand: "Realtek",
    model: "RTL8822CE",
    category: "wifi",
    performanceTier: "budget",
    pricing: { usedMin: 5, usedMax: 12, newMin: 0, newMax: 0 },
    wifiStandard: "WiFi 5 (802.11ac)",
    bluetooth: "Bluetooth 4.2",
    interface: "M.2 Key E",
    specsSummary: "OEM WiFi card from laptops/prebuilts. Upgrade candidate.",
    tags: ["oem", "budget"],
  },
  {
    id: "wifi-intel-be200",
    name: "Intel BE200 WiFi 7",
    brand: "Intel",
    model: "BE200",
    category: "wifi",
    performanceTier: "high",
    pricing: { usedMin: 25, usedMax: 40, newMin: 45, newMax: 60 },
    wifiStandard: "WiFi 7 (802.11be)",
    bluetooth: "Bluetooth 5.4",
    interface: "M.2 Key E",
    specsSummary: "Latest Intel WiFi module. Premium addon for new builds.",
    tags: ["wifi7", "modern"],
  },
  {
    id: "wifi-tp-link-archer-t4u",
    name: "TP-Link Archer T4U USB WiFi Adapter",
    brand: "TP-Link",
    model: "Archer T4U Plus",
    category: "wifi",
    performanceTier: "budget",
    pricing: { usedMin: 10, usedMax: 18, newMin: 25, newMax: 35 },
    wifiStandard: "WiFi 5 (802.11ac)",
    bluetooth: "None",
    interface: "USB",
    specsSummary: "USB dongle. Common cheap addon for office flips.",
    tags: ["usb", "addon"],
  },
  {
    id: "wifi-asus-pce-ax58bt",
    name: "ASUS PCE-AX58BT PCIe WiFi 6",
    brand: "ASUS",
    model: "PCE-AX58BT",
    category: "wifi",
    performanceTier: "mid",
    pricing: { usedMin: 20, usedMax: 35, newMin: 45, newMax: 60 },
    wifiStandard: "WiFi 6 (802.11ax)",
    bluetooth: "Bluetooth 5.0",
    interface: "PCIe",
    specsSummary: "PCIe WiFi card with external antenna. Good for boards without M.2 WiFi.",
    tags: ["pcie", "addon"],
  },
];
