import type { Fans, WiFiModule, OperatingSystem } from "@/lib/types/components";

export const caseFans: Fans[] = [
  {
    id: "fans-120mm-3pack",
    name: "120mm PWM Fans (3-Pack)",
    brand: "Arctic",
    model: "P12 PWM PST 3-Pack",
    category: "fans",
    performanceTier: "budget",
    pricing: { usedMin: 15, usedMax: 25, newMin: 25, newMax: 35 },
    sizeMm: 120,
    quantity: 3,
    rgb: false,
    argb: false,
    pwm: true,
    tags: ["value"],
  },
  {
    id: "fans-120mm-rgb-3pack",
    name: "120mm RGB Fans (3-Pack)",
    brand: "Corsair",
    model: "LL120 RGB 3-Pack",
    category: "fans",
    performanceTier: "mid",
    pricing: { usedMin: 40, usedMax: 60, newMin: 70, newMax: 90 },
    sizeMm: 120,
    quantity: 3,
    rgb: true,
    argb: false,
    pwm: true,
    tags: ["rgb"],
  },
];

export const wifiModules: WiFiModule[] = [
  {
    id: "wifi-intel-ax200",
    name: "Intel AX200 WiFi 6",
    brand: "Intel",
    model: "AX200",
    category: "wifi",
    performanceTier: "mid",
    pricing: { usedMin: 10, usedMax: 20, newMin: 20, newMax: 30 },
    wifiStandard: "WiFi 6 (802.11ax)",
    bluetooth: "Bluetooth 5.0",
    interface: "M.2 Key E",
    tags: ["addon"],
  },
  {
    id: "wifi-intel-ax210",
    name: "Intel AX210 WiFi 6E",
    brand: "Intel",
    model: "AX210",
    category: "wifi",
    performanceTier: "mid",
    pricing: { usedMin: 15, usedMax: 25, newMin: 25, newMax: 35 },
    wifiStandard: "WiFi 6E (802.11ax)",
    bluetooth: "Bluetooth 5.2",
    interface: "M.2 Key E",
    tags: ["addon"],
  },
];

export const operatingSystems: OperatingSystem[] = [
  {
    id: "os-win11-home",
    name: "Windows 11 Home",
    brand: "Microsoft",
    model: "Windows 11 Home",
    category: "os",
    performanceTier: "mid",
    pricing: { usedMin: 0, usedMax: 0, newMin: 100, newMax: 140 },
    version: "Windows 11 Home",
    licenseType: "retail",
    tags: ["os"],
  },
  {
    id: "os-win11-pro",
    name: "Windows 11 Pro",
    brand: "Microsoft",
    model: "Windows 11 Pro",
    category: "os",
    performanceTier: "mid",
    pricing: { usedMin: 0, usedMax: 0, newMin: 140, newMax: 200 },
    version: "Windows 11 Pro",
    licenseType: "retail",
    tags: ["os"],
  },
  {
    id: "os-win10-home",
    name: "Windows 10 Home",
    brand: "Microsoft",
    model: "Windows 10 Home",
    category: "os",
    performanceTier: "budget",
    pricing: { usedMin: 0, usedMax: 0, newMin: 0, newMax: 0 },
    version: "Windows 10 Home",
    licenseType: "oem",
    tags: ["legacy"],
  },
  {
    id: "os-none",
    name: "No OS / Linux",
    brand: "N/A",
    model: "No Operating System",
    category: "os",
    performanceTier: "entry",
    pricing: { usedMin: 0, usedMax: 0, newMin: 0, newMax: 0 },
    version: "None",
    licenseType: "digital",
    tags: ["no-os"],
  },
];
